# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: card_attributes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63\x61rd_attributes.proto*\x88\x01\n\rCardAttribute\x12\x0e\n\nAttrTapped\x10\x01\x12\x11\n\rAttrAttacking\x10\x02\x12\x10\n\x0c\x41ttrFaceDown\x10\x03\x12\r\n\tAttrColor\x10\x04\x12\n\n\x06\x41ttrPT\x10\x05\x12\x12\n\x0e\x41ttrAnnotation\x10\x06\x12\x13\n\x0f\x41ttrDoesntUntap\x10\x07')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'card_attributes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CARDATTRIBUTE._serialized_start=26
  _CARDATTRIBUTE._serialized_end=162
# @@protoc_insertion_point(module_scope)
