# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: card_attributes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='card_attributes.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63\x61rd_attributes.proto*\x88\x01\n\rCardAttribute\x12\x0e\n\nAttrTapped\x10\x01\x12\x11\n\rAttrAttacking\x10\x02\x12\x10\n\x0c\x41ttrFaceDown\x10\x03\x12\r\n\tAttrColor\x10\x04\x12\n\n\x06\x41ttrPT\x10\x05\x12\x12\n\x0e\x41ttrAnnotation\x10\x06\x12\x13\n\x0f\x41ttrDoesntUntap\x10\x07'
)

_CARDATTRIBUTE = _descriptor.EnumDescriptor(
  name='CardAttribute',
  full_name='CardAttribute',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AttrTapped', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AttrAttacking', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AttrFaceDown', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AttrColor', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AttrPT', index=4, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AttrAnnotation', index=5, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AttrDoesntUntap', index=6, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=26,
  serialized_end=162,
)
_sym_db.RegisterEnumDescriptor(_CARDATTRIBUTE)

CardAttribute = enum_type_wrapper.EnumTypeWrapper(_CARDATTRIBUTE)
AttrTapped = 1
AttrAttacking = 2
AttrFaceDown = 3
AttrColor = 4
AttrPT = 5
AttrAnnotation = 6
AttrDoesntUntap = 7


DESCRIPTOR.enum_types_by_name['CardAttribute'] = _CARDATTRIBUTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
