# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_set_sideboard_plan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2
import move_card_to_zone_pb2 as move__card__to__zone__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_set_sideboard_plan.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n command_set_sideboard_plan.proto\x1a\x13game_commands.proto\x1a\x17move_card_to_zone.proto\"v\n\x18\x43ommand_SetSideboardPlan\x12#\n\tmove_list\x18\x01 \x03(\x0b\x32\x10.MoveCard_ToZone25\n\x03\x65xt\x12\x0c.GameCommand\x18\x84\x08 \x01(\x0b\x32\x19.Command_SetSideboardPlan'
  ,
  dependencies=[game__commands__pb2.DESCRIPTOR,move__card__to__zone__pb2.DESCRIPTOR,])




_COMMAND_SETSIDEBOARDPLAN = _descriptor.Descriptor(
  name='Command_SetSideboardPlan',
  full_name='Command_SetSideboardPlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='move_list', full_name='Command_SetSideboardPlan.move_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_SetSideboardPlan.ext', index=0,
      number=1028, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=200,
)

_COMMAND_SETSIDEBOARDPLAN.fields_by_name['move_list'].message_type = move__card__to__zone__pb2._MOVECARD_TOZONE
DESCRIPTOR.message_types_by_name['Command_SetSideboardPlan'] = _COMMAND_SETSIDEBOARDPLAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_SetSideboardPlan = _reflection.GeneratedProtocolMessageType('Command_SetSideboardPlan', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_SETSIDEBOARDPLAN,
  '__module__' : 'command_set_sideboard_plan_pb2'
  # @@protoc_insertion_point(class_scope:Command_SetSideboardPlan)
  })
_sym_db.RegisterMessage(Command_SetSideboardPlan)

_COMMAND_SETSIDEBOARDPLAN.extensions_by_name['ext'].message_type = _COMMAND_SETSIDEBOARDPLAN
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_SETSIDEBOARDPLAN.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
