# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_flip_card.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ommand_flip_card.proto\x1a\x13game_commands.proto\"\x83\x01\n\x10\x43ommand_FlipCard\x12\x0c\n\x04zone\x18\x01 \x01(\t\x12\x13\n\x07\x63\x61rd_id\x18\x02 \x01(\x11:\x02-1\x12\x11\n\tface_down\x18\x03 \x01(\x08\x12\n\n\x02pt\x18\x04 \x01(\t2-\n\x03\x65xt\x12\x0c.GameCommand\x18\xf0\x07 \x01(\x0b\x32\x11.Command_FlipCard')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_flip_card_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_FLIPCARD.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_FLIPCARD._serialized_start=49
  _COMMAND_FLIPCARD._serialized_end=180
# @@protoc_insertion_point(module_scope)
