# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_set_card_counter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_set_card_counter.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x63ommand_set_card_counter.proto\x1a\x13game_commands.proto\"\x9f\x01\n\x16\x43ommand_SetCardCounter\x12\x0c\n\x04zone\x18\x01 \x01(\t\x12\x13\n\x07\x63\x61rd_id\x18\x02 \x01(\x11:\x02-1\x12\x16\n\ncounter_id\x18\x03 \x01(\x11:\x02-1\x12\x15\n\rcounter_value\x18\x04 \x01(\x11\x32\x33\n\x03\x65xt\x12\x0c.GameCommand\x18\xf6\x07 \x01(\x0b\x32\x17.Command_SetCardCounter'
  ,
  dependencies=[game__commands__pb2.DESCRIPTOR,])




_COMMAND_SETCARDCOUNTER = _descriptor.Descriptor(
  name='Command_SetCardCounter',
  full_name='Command_SetCardCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='zone', full_name='Command_SetCardCounter.zone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='card_id', full_name='Command_SetCardCounter.card_id', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter_id', full_name='Command_SetCardCounter.counter_id', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter_value', full_name='Command_SetCardCounter.counter_value', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_SetCardCounter.ext', index=0,
      number=1014, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=215,
)

DESCRIPTOR.message_types_by_name['Command_SetCardCounter'] = _COMMAND_SETCARDCOUNTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_SetCardCounter = _reflection.GeneratedProtocolMessageType('Command_SetCardCounter', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_SETCARDCOUNTER,
  '__module__' : 'command_set_card_counter_pb2'
  # @@protoc_insertion_point(class_scope:Command_SetCardCounter)
  })
_sym_db.RegisterMessage(Command_SetCardCounter)

_COMMAND_SETCARDCOUNTER.extensions_by_name['ext'].message_type = _COMMAND_SETCARDCOUNTER
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_SETCARDCOUNTER.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
