# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_deck_download.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_commands_pb2 as session__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_deck_download.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1b\x63ommand_deck_download.proto\x1a\x16session_commands.proto\"a\n\x14\x43ommand_DeckDownload\x12\x13\n\x07\x64\x65\x63k_id\x18\x01 \x01(\x11:\x02-124\n\x03\x65xt\x12\x0f.SessionCommand\x18\xf4\x07 \x01(\x0b\x32\x15.Command_DeckDownload'
  ,
  dependencies=[session__commands__pb2.DESCRIPTOR,])




_COMMAND_DECKDOWNLOAD = _descriptor.Descriptor(
  name='Command_DeckDownload',
  full_name='Command_DeckDownload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deck_id', full_name='Command_DeckDownload.deck_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_DeckDownload.ext', index=0,
      number=1012, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['Command_DeckDownload'] = _COMMAND_DECKDOWNLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_DeckDownload = _reflection.GeneratedProtocolMessageType('Command_DeckDownload', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DECKDOWNLOAD,
  '__module__' : 'command_deck_download_pb2'
  # @@protoc_insertion_point(class_scope:Command_DeckDownload)
  })
_sym_db.RegisterMessage(Command_DeckDownload)

_COMMAND_DECKDOWNLOAD.extensions_by_name['ext'].message_type = _COMMAND_DECKDOWNLOAD
session__commands__pb2.SessionCommand.RegisterExtension(_COMMAND_DECKDOWNLOAD.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
