# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command_shuffle.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'command_shuffle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommand_shuffle.proto\x1a\x13game_commands.proto\"u\n\x0f\x43ommand_Shuffle\x12\x11\n\tzone_name\x18\x01 \x01(\t\x12\x10\n\x05start\x18\x02 \x01(\x11:\x01\x30\x12\x0f\n\x03\x65nd\x18\x03 \x01(\x11:\x02-12,\n\x03\x65xt\x12\x0c.GameCommand\x18\xeb\x07 \x01(\x0b\x32\x10.Command_Shuffle')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_shuffle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND_SHUFFLE']._serialized_start=46
  _globals['_COMMAND_SHUFFLE']._serialized_end=163
# @@protoc_insertion_point(module_scope)
