# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_stop_dump_zone.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_stop_dump_zone.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x63ommand_stop_dump_zone.proto\x1a\x13game_commands.proto\"o\n\x14\x43ommand_StopDumpZone\x12\x11\n\tplayer_id\x18\x01 \x01(\x11\x12\x11\n\tzone_name\x18\x02 \x01(\t21\n\x03\x65xt\x12\x0c.GameCommand\x18\x81\x08 \x01(\x0b\x32\x15.Command_StopDumpZone'
  ,
  dependencies=[game__commands__pb2.DESCRIPTOR,])




_COMMAND_STOPDUMPZONE = _descriptor.Descriptor(
  name='Command_StopDumpZone',
  full_name='Command_StopDumpZone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='Command_StopDumpZone.player_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zone_name', full_name='Command_StopDumpZone.zone_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_StopDumpZone.ext', index=0,
      number=1025, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=164,
)

DESCRIPTOR.message_types_by_name['Command_StopDumpZone'] = _COMMAND_STOPDUMPZONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_StopDumpZone = _reflection.GeneratedProtocolMessageType('Command_StopDumpZone', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_STOPDUMPZONE,
  '__module__' : 'command_stop_dump_zone_pb2'
  # @@protoc_insertion_point(class_scope:Command_StopDumpZone)
  })
_sym_db.RegisterMessage(Command_StopDumpZone)

_COMMAND_STOPDUMPZONE.extensions_by_name['ext'].message_type = _COMMAND_STOPDUMPZONE
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_STOPDUMPZONE.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
