# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_ready_start.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_ready_start.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63ommand_ready_start.proto\x1a\x13game_commands.proto\"T\n\x12\x43ommand_ReadyStart\x12\r\n\x05ready\x18\x01 \x01(\x08\x32/\n\x03\x65xt\x12\x0c.GameCommand\x18\xf8\x07 \x01(\x0b\x32\x13.Command_ReadyStart'
  ,
  dependencies=[game__commands__pb2.DESCRIPTOR,])




_COMMAND_READYSTART = _descriptor.Descriptor(
  name='Command_ReadyStart',
  full_name='Command_ReadyStart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ready', full_name='Command_ReadyStart.ready', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_ReadyStart.ext', index=0,
      number=1016, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['Command_ReadyStart'] = _COMMAND_READYSTART
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_ReadyStart = _reflection.GeneratedProtocolMessageType('Command_ReadyStart', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_READYSTART,
  '__module__' : 'command_ready_start_pb2'
  # @@protoc_insertion_point(class_scope:Command_ReadyStart)
  })
_sym_db.RegisterMessage(Command_ReadyStart)

_COMMAND_READYSTART.extensions_by_name['ext'].message_type = _COMMAND_READYSTART
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_READYSTART.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
