# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_roll_die.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_roll_die.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63ommand_roll_die.proto\x1a\x13game_commands.proto\"N\n\x0f\x43ommand_RollDie\x12\r\n\x05sides\x18\x01 \x01(\r2,\n\x03\x65xt\x12\x0c.GameCommand\x18\xed\x07 \x01(\x0b\x32\x10.Command_RollDie'
  ,
  dependencies=[game__commands__pb2.DESCRIPTOR,])




_COMMAND_ROLLDIE = _descriptor.Descriptor(
  name='Command_RollDie',
  full_name='Command_RollDie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sides', full_name='Command_RollDie.sides', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_RollDie.ext', index=0,
      number=1005, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['Command_RollDie'] = _COMMAND_ROLLDIE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_RollDie = _reflection.GeneratedProtocolMessageType('Command_RollDie', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_ROLLDIE,
  '__module__' : 'command_roll_die_pb2'
  # @@protoc_insertion_point(class_scope:Command_RollDie)
  })
_sym_db.RegisterMessage(Command_RollDie)

_COMMAND_ROLLDIE.extensions_by_name['ext'].message_type = _COMMAND_ROLLDIE
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_ROLLDIE.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
