# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_deck_new_dir.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_commands_pb2 as session__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_deck_new_dir.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1a\x63ommand_deck_new_dir.proto\x1a\x16session_commands.proto\"h\n\x12\x43ommand_DeckNewDir\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08\x64ir_name\x18\x02 \x01(\t22\n\x03\x65xt\x12\x0f.SessionCommand\x18\xf1\x07 \x01(\x0b\x32\x13.Command_DeckNewDir'
  ,
  dependencies=[session__commands__pb2.DESCRIPTOR,])




_COMMAND_DECKNEWDIR = _descriptor.Descriptor(
  name='Command_DeckNewDir',
  full_name='Command_DeckNewDir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='Command_DeckNewDir.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dir_name', full_name='Command_DeckNewDir.dir_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_DeckNewDir.ext', index=0,
      number=1009, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['Command_DeckNewDir'] = _COMMAND_DECKNEWDIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_DeckNewDir = _reflection.GeneratedProtocolMessageType('Command_DeckNewDir', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DECKNEWDIR,
  '__module__' : 'command_deck_new_dir_pb2'
  # @@protoc_insertion_point(class_scope:Command_DeckNewDir)
  })
_sym_db.RegisterMessage(Command_DeckNewDir)

_COMMAND_DECKNEWDIR.extensions_by_name['ext'].message_type = _COMMAND_DECKNEWDIR
session__commands__pb2.SessionCommand.RegisterExtension(_COMMAND_DECKNEWDIR.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
