# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_deck_upload.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_commands_pb2 as session__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_deck_upload.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63ommand_deck_upload.proto\x1a\x16session_commands.proto\"z\n\x12\x43ommand_DeckUpload\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65\x63k_id\x18\x02 \x01(\r\x12\x11\n\tdeck_list\x18\x03 \x01(\t22\n\x03\x65xt\x12\x0f.SessionCommand\x18\xf5\x07 \x01(\x0b\x32\x13.Command_DeckUpload'
  ,
  dependencies=[session__commands__pb2.DESCRIPTOR,])




_COMMAND_DECKUPLOAD = _descriptor.Descriptor(
  name='Command_DeckUpload',
  full_name='Command_DeckUpload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='Command_DeckUpload.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deck_id', full_name='Command_DeckUpload.deck_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deck_list', full_name='Command_DeckUpload.deck_list', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_DeckUpload.ext', index=0,
      number=1013, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['Command_DeckUpload'] = _COMMAND_DECKUPLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_DeckUpload = _reflection.GeneratedProtocolMessageType('Command_DeckUpload', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DECKUPLOAD,
  '__module__' : 'command_deck_upload_pb2'
  # @@protoc_insertion_point(class_scope:Command_DeckUpload)
  })
_sym_db.RegisterMessage(Command_DeckUpload)

_COMMAND_DECKUPLOAD.extensions_by_name['ext'].message_type = _COMMAND_DECKUPLOAD
session__commands__pb2.SessionCommand.RegisterExtension(_COMMAND_DECKUPLOAD.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
