# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_deck_del.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_commands_pb2 as session__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_deck_del.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x63ommand_deck_del.proto\x1a\x16session_commands.proto\"W\n\x0f\x43ommand_DeckDel\x12\x13\n\x07\x64\x65\x63k_id\x18\x01 \x01(\x11:\x02-12/\n\x03\x65xt\x12\x0f.SessionCommand\x18\xf3\x07 \x01(\x0b\x32\x10.Command_DeckDel'
  ,
  dependencies=[session__commands__pb2.DESCRIPTOR,])




_COMMAND_DECKDEL = _descriptor.Descriptor(
  name='Command_DeckDel',
  full_name='Command_DeckDel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deck_id', full_name='Command_DeckDel.deck_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_DeckDel.ext', index=0,
      number=1011, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['Command_DeckDel'] = _COMMAND_DECKDEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_DeckDel = _reflection.GeneratedProtocolMessageType('Command_DeckDel', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DECKDEL,
  '__module__' : 'command_deck_del_pb2'
  # @@protoc_insertion_point(class_scope:Command_DeckDel)
  })
_sym_db.RegisterMessage(Command_DeckDel)

_COMMAND_DECKDEL.extensions_by_name['ext'].message_type = _COMMAND_DECKDEL
session__commands__pb2.SessionCommand.RegisterExtension(_COMMAND_DECKDEL.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
