# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_replay_modify_match.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_commands_pb2 as session__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_replay_modify_match.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!command_replay_modify_match.proto\x1a\x16session_commands.proto\"\x80\x01\n\x19\x43ommand_ReplayModifyMatch\x12\x13\n\x07game_id\x18\x01 \x01(\x11:\x02-1\x12\x13\n\x0b\x64o_not_hide\x18\x02 \x01(\x08\x32\x39\n\x03\x65xt\x12\x0f.SessionCommand\x18\xce\x08 \x01(\x0b\x32\x1a.Command_ReplayModifyMatch'
  ,
  dependencies=[session__commands__pb2.DESCRIPTOR,])




_COMMAND_REPLAYMODIFYMATCH = _descriptor.Descriptor(
  name='Command_ReplayModifyMatch',
  full_name='Command_ReplayModifyMatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='Command_ReplayModifyMatch.game_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='do_not_hide', full_name='Command_ReplayModifyMatch.do_not_hide', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_ReplayModifyMatch.ext', index=0,
      number=1102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=190,
)

DESCRIPTOR.message_types_by_name['Command_ReplayModifyMatch'] = _COMMAND_REPLAYMODIFYMATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_ReplayModifyMatch = _reflection.GeneratedProtocolMessageType('Command_ReplayModifyMatch', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_REPLAYMODIFYMATCH,
  '__module__' : 'command_replay_modify_match_pb2'
  # @@protoc_insertion_point(class_scope:Command_ReplayModifyMatch)
  })
_sym_db.RegisterMessage(Command_ReplayModifyMatch)

_COMMAND_REPLAYMODIFYMATCH.extensions_by_name['ext'].message_type = _COMMAND_REPLAYMODIFYMATCH
session__commands__pb2.SessionCommand.RegisterExtension(_COMMAND_REPLAYMODIFYMATCH.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
