# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_concede.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_concede.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63ommand_concede.proto\x1a\x13game_commands.proto\"?\n\x0f\x43ommand_Concede2,\n\x03\x65xt\x12\x0c.GameCommand\x18\xf9\x07 \x01(\x0b\x32\x10.Command_Concede\"C\n\x11\x43ommand_Unconcede2.\n\x03\x65xt\x12\x0c.GameCommand\x18\x88\x08 \x01(\x0b\x32\x12.Command_Unconcede'
  ,
  dependencies=[game__commands__pb2.DESCRIPTOR,])




_COMMAND_CONCEDE = _descriptor.Descriptor(
  name='Command_Concede',
  full_name='Command_Concede',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_Concede.ext', index=0,
      number=1017, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=109,
)


_COMMAND_UNCONCEDE = _descriptor.Descriptor(
  name='Command_Unconcede',
  full_name='Command_Unconcede',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_Unconcede.ext', index=0,
      number=1032, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['Command_Concede'] = _COMMAND_CONCEDE
DESCRIPTOR.message_types_by_name['Command_Unconcede'] = _COMMAND_UNCONCEDE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_Concede = _reflection.GeneratedProtocolMessageType('Command_Concede', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_CONCEDE,
  '__module__' : 'command_concede_pb2'
  # @@protoc_insertion_point(class_scope:Command_Concede)
  })
_sym_db.RegisterMessage(Command_Concede)

Command_Unconcede = _reflection.GeneratedProtocolMessageType('Command_Unconcede', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_UNCONCEDE,
  '__module__' : 'command_concede_pb2'
  # @@protoc_insertion_point(class_scope:Command_Unconcede)
  })
_sym_db.RegisterMessage(Command_Unconcede)

_COMMAND_CONCEDE.extensions_by_name['ext'].message_type = _COMMAND_CONCEDE
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_CONCEDE.extensions_by_name['ext'])
_COMMAND_UNCONCEDE.extensions_by_name['ext'].message_type = _COMMAND_UNCONCEDE
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_UNCONCEDE.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
