# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_set_sideboard_lock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_set_sideboard_lock.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n command_set_sideboard_lock.proto\x1a\x13game_commands.proto\"a\n\x18\x43ommand_SetSideboardLock\x12\x0e\n\x06locked\x18\x01 \x01(\x08\x32\x35\n\x03\x65xt\x12\x0c.GameCommand\x18\x86\x08 \x01(\x0b\x32\x19.Command_SetSideboardLock'
  ,
  dependencies=[game__commands__pb2.DESCRIPTOR,])




_COMMAND_SETSIDEBOARDLOCK = _descriptor.Descriptor(
  name='Command_SetSideboardLock',
  full_name='Command_SetSideboardLock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='locked', full_name='Command_SetSideboardLock.locked', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_SetSideboardLock.ext', index=0,
      number=1030, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['Command_SetSideboardLock'] = _COMMAND_SETSIDEBOARDLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_SetSideboardLock = _reflection.GeneratedProtocolMessageType('Command_SetSideboardLock', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_SETSIDEBOARDLOCK,
  '__module__' : 'command_set_sideboard_lock_pb2'
  # @@protoc_insertion_point(class_scope:Command_SetSideboardLock)
  })
_sym_db.RegisterMessage(Command_SetSideboardLock)

_COMMAND_SETSIDEBOARDLOCK.extensions_by_name['ext'].message_type = _COMMAND_SETSIDEBOARDLOCK
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_SETSIDEBOARDLOCK.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
