# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_kick_from_game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command_kick_from_game.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x63ommand_kick_from_game.proto\x1a\x13game_commands.proto\"`\n\x14\x43ommand_KickFromGame\x12\x15\n\tplayer_id\x18\x01 \x01(\x11:\x02-121\n\x03\x65xt\x12\x0c.GameCommand\x18\xe8\x07 \x01(\x0b\x32\x15.Command_KickFromGame'
  ,
  dependencies=[game__commands__pb2.DESCRIPTOR,])




_COMMAND_KICKFROMGAME = _descriptor.Descriptor(
  name='Command_KickFromGame',
  full_name='Command_KickFromGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='Command_KickFromGame.player_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_KickFromGame.ext', index=0,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['Command_KickFromGame'] = _COMMAND_KICKFROMGAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command_KickFromGame = _reflection.GeneratedProtocolMessageType('Command_KickFromGame', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_KICKFROMGAME,
  '__module__' : 'command_kick_from_game_pb2'
  # @@protoc_insertion_point(class_scope:Command_KickFromGame)
  })
_sym_db.RegisterMessage(Command_KickFromGame)

_COMMAND_KICKFROMGAME.extensions_by_name['ext'].message_type = _COMMAND_KICKFROMGAME
game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_KICKFROMGAME.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
