# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: context_undo_draw.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_context_pb2 as game__event__context__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='context_undo_draw.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x63ontext_undo_draw.proto\x1a\x18game_event_context.proto\"F\n\x10\x43ontext_UndoDraw22\n\x03\x65xt\x12\x11.GameEventContext\x18\xeb\x07 \x01(\x0b\x32\x11.Context_UndoDraw'
  ,
  dependencies=[game__event__context__pb2.DESCRIPTOR,])




_CONTEXT_UNDODRAW = _descriptor.Descriptor(
  name='Context_UndoDraw',
  full_name='Context_UndoDraw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Context_UndoDraw.ext', index=0,
      number=1003, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['Context_UndoDraw'] = _CONTEXT_UNDODRAW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Context_UndoDraw = _reflection.GeneratedProtocolMessageType('Context_UndoDraw', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXT_UNDODRAW,
  '__module__' : 'context_undo_draw_pb2'
  # @@protoc_insertion_point(class_scope:Context_UndoDraw)
  })
_sym_db.RegisterMessage(Context_UndoDraw)

_CONTEXT_UNDODRAW.extensions_by_name['ext'].message_type = _CONTEXT_UNDODRAW
game__event__context__pb2.GameEventContext.RegisterExtension(_CONTEXT_UNDODRAW.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
