# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: context_set_sideboard_lock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_context_pb2 as game__event__context__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n context_set_sideboard_lock.proto\x1a\x18game_event_context.proto\"V\n\x18\x43ontext_SetSideboardLock2:\n\x03\x65xt\x12\x11.GameEventContext\x18\xf0\x07 \x01(\x0b\x32\x19.Context_SetSideboardLock')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'context_set_sideboard_lock_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__context__pb2.GameEventContext.RegisterExtension(_CONTEXT_SETSIDEBOARDLOCK.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _CONTEXT_SETSIDEBOARDLOCK._serialized_start=62
  _CONTEXT_SETSIDEBOARDLOCK._serialized_end=148
# @@protoc_insertion_point(module_scope)
