# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: context_set_sideboard_lock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_context_pb2 as game__event__context__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='context_set_sideboard_lock.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n context_set_sideboard_lock.proto\x1a\x18game_event_context.proto\"V\n\x18\x43ontext_SetSideboardLock2:\n\x03\x65xt\x12\x11.GameEventContext\x18\xf0\x07 \x01(\x0b\x32\x19.Context_SetSideboardLock'
  ,
  dependencies=[game__event__context__pb2.DESCRIPTOR,])




_CONTEXT_SETSIDEBOARDLOCK = _descriptor.Descriptor(
  name='Context_SetSideboardLock',
  full_name='Context_SetSideboardLock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Context_SetSideboardLock.ext', index=0,
      number=1008, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['Context_SetSideboardLock'] = _CONTEXT_SETSIDEBOARDLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Context_SetSideboardLock = _reflection.GeneratedProtocolMessageType('Context_SetSideboardLock', (_message.Message,), {
  'DESCRIPTOR' : _CONTEXT_SETSIDEBOARDLOCK,
  '__module__' : 'context_set_sideboard_lock_pb2'
  # @@protoc_insertion_point(class_scope:Context_SetSideboardLock)
  })
_sym_db.RegisterMessage(Context_SetSideboardLock)

_CONTEXT_SETSIDEBOARDLOCK.extensions_by_name['ext'].message_type = _CONTEXT_SETSIDEBOARDLOCK
game__event__context__pb2.GameEventContext.RegisterExtension(_CONTEXT_SETSIDEBOARDLOCK.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
