# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_change_zone_properties.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"event_change_zone_properties.proto\x1a\x10game_event.proto\"\xa7\x01\n\x1a\x45vent_ChangeZoneProperties\x12\x11\n\tzone_name\x18\x01 \x01(\t\x12\x1e\n\x16\x61lways_reveal_top_card\x18\n \x01(\x08\x12\x1f\n\x17\x61lways_look_at_top_card\x18\x0b \x01(\x08\x32\x35\n\x03\x65xt\x12\n.GameEvent\x18\xe4\x0f \x01(\x0b\x32\x1b.Event_ChangeZoneProperties')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_change_zone_properties_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_CHANGEZONEPROPERTIES.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_CHANGEZONEPROPERTIES._serialized_start=57
  _EVENT_CHANGEZONEPROPERTIES._serialized_end=224
# @@protoc_insertion_point(module_scope)
