# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_game_joined.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_event_pb2 as session__event__pb2
import serverinfo_game_pb2 as serverinfo__game__pb2
import serverinfo_gametype_pb2 as serverinfo__gametype__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65vent_game_joined.proto\x1a\x13session_event.proto\x1a\x15serverinfo_game.proto\x1a\x19serverinfo_gametype.proto\"\xe9\x01\n\x10\x45vent_GameJoined\x12#\n\tgame_info\x18\x01 \x01(\x0b\x32\x10.ServerInfo_Game\x12(\n\ngame_types\x18\x02 \x03(\x0b\x32\x14.ServerInfo_GameType\x12\x0f\n\x07host_id\x18\x03 \x01(\x11\x12\x11\n\tplayer_id\x18\x04 \x01(\x11\x12\x11\n\tspectator\x18\x05 \x01(\x08\x12\x10\n\x08resuming\x18\x06 \x01(\x08\x12\r\n\x05judge\x18\x07 \x01(\x08\x32.\n\x03\x65xt\x12\r.SessionEvent\x18\xf1\x07 \x01(\x0b\x32\x11.Event_GameJoined')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_game_joined_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  session__event__pb2.SessionEvent.RegisterExtension(_EVENT_GAMEJOINED.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_GAMEJOINED._serialized_start=99
  _EVENT_GAMEJOINED._serialized_end=332
# @@protoc_insertion_point(module_scope)
