# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_remove_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import room_event_pb2 as room__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65vent_remove_messages.proto\x1a\x10room_event.proto\"e\n\x14\x45vent_RemoveMessages\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\r2/\n\x03\x65xt\x12\n.RoomEvent\x18\xec\x07 \x01(\x0b\x32\x15.Event_RemoveMessages')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_remove_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  room__event__pb2.RoomEvent.RegisterExtension(_EVENT_REMOVEMESSAGES.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_REMOVEMESSAGES._serialized_start=49
  _EVENT_REMOVEMESSAGES._serialized_end=150
# @@protoc_insertion_point(module_scope)
