# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_list_rooms.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'event_list_rooms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_event_pb2 as session__event__pb2
import serverinfo_room_pb2 as serverinfo__room__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65vent_list_rooms.proto\x1a\x13session_event.proto\x1a\x15serverinfo_room.proto\"e\n\x0f\x45vent_ListRooms\x12#\n\troom_list\x18\x01 \x03(\x0b\x32\x10.ServerInfo_Room2-\n\x03\x65xt\x12\r.SessionEvent\x18\xec\x07 \x01(\x0b\x32\x10.Event_ListRooms')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_list_rooms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT_LISTROOMS']._serialized_start=70
  _globals['_EVENT_LISTROOMS']._serialized_end=171
# @@protoc_insertion_point(module_scope)
