# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_move_card.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65vent_move_card.proto\x1a\x10game_event.proto\"\xc5\x02\n\x0e\x45vent_MoveCard\x12\x13\n\x07\x63\x61rd_id\x18\x01 \x01(\x11:\x02-1\x12\x11\n\tcard_name\x18\x02 \x01(\t\x12\x1b\n\x0fstart_player_id\x18\x03 \x01(\x11:\x02-1\x12\x12\n\nstart_zone\x18\x04 \x01(\t\x12\x14\n\x08position\x18\x05 \x01(\x11:\x02-1\x12\x1c\n\x10target_player_id\x18\x06 \x01(\x11:\x02-1\x12\x13\n\x0btarget_zone\x18\x07 \x01(\t\x12\r\n\x01x\x18\x08 \x01(\x11:\x02-1\x12\r\n\x01y\x18\t \x01(\x11:\x02-1\x12\x17\n\x0bnew_card_id\x18\n \x01(\x11:\x02-1\x12\x11\n\tface_down\x18\x0b \x01(\x08\x12\x1c\n\x14new_card_provider_id\x18\x0c \x01(\t2)\n\x03\x65xt\x12\n.GameEvent\x18\xd9\x0f \x01(\x0b\x32\x0f.Event_MoveCard')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_move_card_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_MOVECARD.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_MOVECARD._serialized_start=44
  _EVENT_MOVECARD._serialized_end=369
# @@protoc_insertion_point(module_scope)
