# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_set_active_player.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65vent_set_active_player.proto\x1a\x10game_event.proto\"c\n\x15\x45vent_SetActivePlayer\x12\x18\n\x10\x61\x63tive_player_id\x18\x01 \x01(\x11\x32\x30\n\x03\x65xt\x12\n.GameEvent\x18\xe0\x0f \x01(\x0b\x32\x16.Event_SetActivePlayer')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_set_active_player_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_SETACTIVEPLAYER.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_SETACTIVEPLAYER._serialized_start=51
  _EVENT_SETACTIVEPLAYER._serialized_end=150
# @@protoc_insertion_point(module_scope)
