# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_game_host_changed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event_game_host_changed.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x65vent_game_host_changed.proto\x1a\x10game_event.proto\"I\n\x15\x45vent_GameHostChanged20\n\x03\x65xt\x12\n.GameEvent\x18\xeb\x07 \x01(\x0b\x32\x16.Event_GameHostChanged'
  ,
  dependencies=[game__event__pb2.DESCRIPTOR,])




_EVENT_GAMEHOSTCHANGED = _descriptor.Descriptor(
  name='Event_GameHostChanged',
  full_name='Event_GameHostChanged',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Event_GameHostChanged.ext', index=0,
      number=1003, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['Event_GameHostChanged'] = _EVENT_GAMEHOSTCHANGED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event_GameHostChanged = _reflection.GeneratedProtocolMessageType('Event_GameHostChanged', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_GAMEHOSTCHANGED,
  '__module__' : 'event_game_host_changed_pb2'
  # @@protoc_insertion_point(class_scope:Event_GameHostChanged)
  })
_sym_db.RegisterMessage(Event_GameHostChanged)

_EVENT_GAMEHOSTCHANGED.extensions_by_name['ext'].message_type = _EVENT_GAMEHOSTCHANGED
game__event__pb2.GameEvent.RegisterExtension(_EVENT_GAMEHOSTCHANGED.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
