# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_draw_cards.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2
import serverinfo_card_pb2 as serverinfo__card__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65vent_draw_cards.proto\x1a\x10game_event.proto\x1a\x15serverinfo_card.proto\"n\n\x0f\x45vent_DrawCards\x12\x0e\n\x06number\x18\x01 \x01(\x11\x12\x1f\n\x05\x63\x61rds\x18\x02 \x03(\x0b\x32\x10.ServerInfo_Card2*\n\x03\x65xt\x12\n.GameEvent\x18\xd5\x0f \x01(\x0b\x32\x10.Event_DrawCards')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_draw_cards_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_DRAWCARDS.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_DRAWCARDS._serialized_start=67
  _EVENT_DRAWCARDS._serialized_end=177
# @@protoc_insertion_point(module_scope)
