# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_shuffle.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event_shuffle.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x65vent_shuffle.proto\x1a\x10game_event.proto\"o\n\rEvent_Shuffle\x12\x11\n\tzone_name\x18\x01 \x01(\t\x12\x10\n\x05start\x18\x02 \x01(\x11:\x01\x30\x12\x0f\n\x03\x65nd\x18\x03 \x01(\x11:\x02-12(\n\x03\x65xt\x12\n.GameEvent\x18\xd7\x0f \x01(\x0b\x32\x0e.Event_Shuffle'
  ,
  dependencies=[game__event__pb2.DESCRIPTOR,])




_EVENT_SHUFFLE = _descriptor.Descriptor(
  name='Event_Shuffle',
  full_name='Event_Shuffle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='zone_name', full_name='Event_Shuffle.zone_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='Event_Shuffle.start', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='Event_Shuffle.end', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Event_Shuffle.ext', index=0,
      number=2007, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['Event_Shuffle'] = _EVENT_SHUFFLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event_Shuffle = _reflection.GeneratedProtocolMessageType('Event_Shuffle', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_SHUFFLE,
  '__module__' : 'event_shuffle_pb2'
  # @@protoc_insertion_point(class_scope:Event_Shuffle)
  })
_sym_db.RegisterMessage(Event_Shuffle)

_EVENT_SHUFFLE.extensions_by_name['ext'].message_type = _EVENT_SHUFFLE
game__event__pb2.GameEvent.RegisterExtension(_EVENT_SHUFFLE.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
