# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_set_counter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='event_set_counter.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x65vent_set_counter.proto\x1a\x10game_event.proto\"b\n\x10\x45vent_SetCounter\x12\x12\n\ncounter_id\x18\x01 \x01(\x11\x12\r\n\x05value\x18\x02 \x01(\x11\x32+\n\x03\x65xt\x12\n.GameEvent\x18\xd3\x0f \x01(\x0b\x32\x11.Event_SetCounter'
  ,
  dependencies=[game__event__pb2.DESCRIPTOR,])




_EVENT_SETCOUNTER = _descriptor.Descriptor(
  name='Event_SetCounter',
  full_name='Event_SetCounter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='counter_id', full_name='Event_SetCounter.counter_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Event_SetCounter.value', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Event_SetCounter.ext', index=0,
      number=2003, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['Event_SetCounter'] = _EVENT_SETCOUNTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event_SetCounter = _reflection.GeneratedProtocolMessageType('Event_SetCounter', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_SETCOUNTER,
  '__module__' : 'event_set_counter_pb2'
  # @@protoc_insertion_point(class_scope:Event_SetCounter)
  })
_sym_db.RegisterMessage(Event_SetCounter)

_EVENT_SETCOUNTER.extensions_by_name['ext'].message_type = _EVENT_SETCOUNTER
game__event__pb2.GameEvent.RegisterExtension(_EVENT_SETCOUNTER.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
