# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_join.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'event_join.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2
import serverinfo_playerproperties_pb2 as serverinfo__playerproperties__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65vent_join.proto\x1a\x10game_event.proto\x1a!serverinfo_playerproperties.proto\"l\n\nEvent_Join\x12\x37\n\x11player_properties\x18\x01 \x01(\x0b\x32\x1c.ServerInfo_PlayerProperties2%\n\x03\x65xt\x12\n.GameEvent\x18\xe8\x07 \x01(\x0b\x32\x0b.Event_Join')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_join_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT_JOIN']._serialized_start=73
  _globals['_EVENT_JOIN']._serialized_end=181
# @@protoc_insertion_point(module_scope)
