# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_replay_added.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_event_pb2 as session__event__pb2
import serverinfo_replay_match_pb2 as serverinfo__replay__match__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65vent_replay_added.proto\x1a\x13session_event.proto\x1a\x1dserverinfo_replay_match.proto\"q\n\x11\x45vent_ReplayAdded\x12+\n\nmatch_info\x18\x01 \x01(\x0b\x32\x17.ServerInfo_ReplayMatch2/\n\x03\x65xt\x12\r.SessionEvent\x18\xcc\x08 \x01(\x0b\x32\x12.Event_ReplayAdded')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_replay_added_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  session__event__pb2.SessionEvent.RegisterExtension(_EVENT_REPLAYADDED.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_REPLAYADDED._serialized_start=80
  _EVENT_REPLAYADDED._serialized_end=193
# @@protoc_insertion_point(module_scope)
