# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game_event.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10game_event.proto\"\xfb\x04\n\tGameEvent\x12\x15\n\tplayer_id\x18\x01 \x01(\x11:\x02-1\"\xcc\x04\n\rGameEventType\x12\t\n\x04JOIN\x10\xe8\x07\x12\n\n\x05LEAVE\x10\xe9\x07\x12\x10\n\x0bGAME_CLOSED\x10\xea\x07\x12\x16\n\x11GAME_HOST_CHANGED\x10\xeb\x07\x12\x0b\n\x06KICKED\x10\xec\x07\x12\x17\n\x12GAME_STATE_CHANGED\x10\xed\x07\x12\x1e\n\x19PLAYER_PROPERTIES_CHANGED\x10\xef\x07\x12\r\n\x08GAME_SAY\x10\xf1\x07\x12\x11\n\x0c\x43REATE_ARROW\x10\xd0\x0f\x12\x11\n\x0c\x44\x45LETE_ARROW\x10\xd1\x0f\x12\x13\n\x0e\x43REATE_COUNTER\x10\xd2\x0f\x12\x10\n\x0bSET_COUNTER\x10\xd3\x0f\x12\x10\n\x0b\x44\x45L_COUNTER\x10\xd4\x0f\x12\x0f\n\nDRAW_CARDS\x10\xd5\x0f\x12\x11\n\x0cREVEAL_CARDS\x10\xd6\x0f\x12\x0c\n\x07SHUFFLE\x10\xd7\x0f\x12\r\n\x08ROLL_DIE\x10\xd8\x0f\x12\x0e\n\tMOVE_CARD\x10\xd9\x0f\x12\x0e\n\tFLIP_CARD\x10\xda\x0f\x12\x11\n\x0c\x44\x45STROY_CARD\x10\xdb\x0f\x12\x10\n\x0b\x41TTACH_CARD\x10\xdc\x0f\x12\x11\n\x0c\x43REATE_TOKEN\x10\xdd\x0f\x12\x12\n\rSET_CARD_ATTR\x10\xde\x0f\x12\x15\n\x10SET_CARD_COUNTER\x10\xdf\x0f\x12\x16\n\x11SET_ACTIVE_PLAYER\x10\xe0\x0f\x12\x15\n\x10SET_ACTIVE_PHASE\x10\xe1\x0f\x12\x0e\n\tDUMP_ZONE\x10\xe2\x0f\x12\x13\n\x0eSTOP_DUMP_ZONE\x10\xe3\x0f\x12\x1b\n\x16\x43HANGE_ZONE_PROPERTIES\x10\xe4\x0f\x12\x11\n\x0cREVERSE_TURN\x10\xe5\x0f*\x08\x08\x64\x10\x80\x80\x80\x80\x02'
)



_GAMEEVENT_GAMEEVENTTYPE = _descriptor.EnumDescriptor(
  name='GameEventType',
  full_name='GameEvent.GameEventType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=0, number=1000,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEAVE', index=1, number=1001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_CLOSED', index=2, number=1002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_HOST_CHANGED', index=3, number=1003,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KICKED', index=4, number=1004,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_STATE_CHANGED', index=5, number=1005,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_PROPERTIES_CHANGED', index=6, number=1007,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_SAY', index=7, number=1009,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ARROW', index=8, number=2000,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELETE_ARROW', index=9, number=2001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREATE_COUNTER', index=10, number=2002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_COUNTER', index=11, number=2003,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEL_COUNTER', index=12, number=2004,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DRAW_CARDS', index=13, number=2005,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVEAL_CARDS', index=14, number=2006,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUFFLE', index=15, number=2007,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLL_DIE', index=16, number=2008,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOVE_CARD', index=17, number=2009,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLIP_CARD', index=18, number=2010,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DESTROY_CARD', index=19, number=2011,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ATTACH_CARD', index=20, number=2012,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREATE_TOKEN', index=21, number=2013,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_CARD_ATTR', index=22, number=2014,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_CARD_COUNTER', index=23, number=2015,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_ACTIVE_PLAYER', index=24, number=2016,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_ACTIVE_PHASE', index=25, number=2017,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DUMP_ZONE', index=26, number=2018,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP_DUMP_ZONE', index=27, number=2019,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHANGE_ZONE_PROPERTIES', index=28, number=2020,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVERSE_TURN', index=29, number=2021,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=58,
  serialized_end=646,
)
_sym_db.RegisterEnumDescriptor(_GAMEEVENT_GAMEEVENTTYPE)


_GAMEEVENT = _descriptor.Descriptor(
  name='GameEvent',
  full_name='GameEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='GameEvent.player_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GAMEEVENT_GAMEEVENTTYPE,
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(100, 536870912), ],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=656,
)

_GAMEEVENT_GAMEEVENTTYPE.containing_type = _GAMEEVENT
DESCRIPTOR.message_types_by_name['GameEvent'] = _GAMEEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameEvent = _reflection.GeneratedProtocolMessageType('GameEvent', (_message.Message,), {
  'DESCRIPTOR' : _GAMEEVENT,
  '__module__' : 'game_event_pb2'
  # @@protoc_insertion_point(class_scope:GameEvent)
  })
_sym_db.RegisterMessage(GameEvent)


# @@protoc_insertion_point(module_scope)
