# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_replay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import serverinfo_game_pb2 as serverinfo__game__pb2
import game_event_container_pb2 as game__event__container__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='game_replay.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11game_replay.proto\x1a\x15serverinfo_game.proto\x1a\x1agame_event_container.proto\"\x87\x01\n\nGameReplay\x12\x11\n\treplay_id\x18\x01 \x01(\x04\x12#\n\tgame_info\x18\x02 \x01(\x0b\x32\x10.ServerInfo_Game\x12\'\n\nevent_list\x18\x03 \x03(\x0b\x32\x13.GameEventContainer\x12\x18\n\x10\x64uration_seconds\x18\x04 \x01(\r'
  ,
  dependencies=[serverinfo__game__pb2.DESCRIPTOR,game__event__container__pb2.DESCRIPTOR,])




_GAMEREPLAY = _descriptor.Descriptor(
  name='GameReplay',
  full_name='GameReplay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='replay_id', full_name='GameReplay.replay_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_info', full_name='GameReplay.game_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_list', full_name='GameReplay.event_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_seconds', full_name='GameReplay.duration_seconds', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=208,
)

_GAMEREPLAY.fields_by_name['game_info'].message_type = serverinfo__game__pb2._SERVERINFO_GAME
_GAMEREPLAY.fields_by_name['event_list'].message_type = game__event__container__pb2._GAMEEVENTCONTAINER
DESCRIPTOR.message_types_by_name['GameReplay'] = _GAMEREPLAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameReplay = _reflection.GeneratedProtocolMessageType('GameReplay', (_message.Message,), {
  'DESCRIPTOR' : _GAMEREPLAY,
  '__module__' : 'game_replay_pb2'
  # @@protoc_insertion_point(class_scope:GameReplay)
  })
_sym_db.RegisterMessage(GameReplay)


# @@protoc_insertion_point(module_scope)
