# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_commands.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game_commands.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13game_commands.proto\"\xb4\x05\n\x0bGameCommand\"\x9a\x05\n\x0fGameCommandType\x12\x13\n\x0eKICK_FROM_GAME\x10\xe8\x07\x12\x0f\n\nLEAVE_GAME\x10\xe9\x07\x12\r\n\x08GAME_SAY\x10\xea\x07\x12\x0c\n\x07SHUFFLE\x10\xeb\x07\x12\r\n\x08MULLIGAN\x10\xec\x07\x12\r\n\x08ROLL_DIE\x10\xed\x07\x12\x0f\n\nDRAW_CARDS\x10\xee\x07\x12\x0e\n\tUNDO_DRAW\x10\xef\x07\x12\x0e\n\tFLIP_CARD\x10\xf0\x07\x12\x10\n\x0b\x41TTACH_CARD\x10\xf1\x07\x12\x11\n\x0c\x43REATE_TOKEN\x10\xf2\x07\x12\x11\n\x0c\x43REATE_ARROW\x10\xf3\x07\x12\x11\n\x0c\x44\x45LETE_ARROW\x10\xf4\x07\x12\x12\n\rSET_CARD_ATTR\x10\xf5\x07\x12\x15\n\x10SET_CARD_COUNTER\x10\xf6\x07\x12\x15\n\x10INC_CARD_COUNTER\x10\xf7\x07\x12\x10\n\x0bREADY_START\x10\xf8\x07\x12\x0c\n\x07\x43ONCEDE\x10\xf9\x07\x12\x10\n\x0bINC_COUNTER\x10\xfa\x07\x12\x13\n\x0e\x43REATE_COUNTER\x10\xfb\x07\x12\x10\n\x0bSET_COUNTER\x10\xfc\x07\x12\x10\n\x0b\x44\x45L_COUNTER\x10\xfd\x07\x12\x0e\n\tNEXT_TURN\x10\xfe\x07\x12\x15\n\x10SET_ACTIVE_PHASE\x10\xff\x07\x12\x0e\n\tDUMP_ZONE\x10\x80\x08\x12\x13\n\x0eSTOP_DUMP_ZONE\x10\x81\x08\x12\x11\n\x0cREVEAL_CARDS\x10\x82\x08\x12\x0e\n\tMOVE_CARD\x10\x83\x08\x12\x17\n\x12SET_SIDEBOARD_PLAN\x10\x84\x08\x12\x10\n\x0b\x44\x45\x43K_SELECT\x10\x85\x08\x12\x17\n\x12SET_SIDEBOARD_LOCK\x10\x86\x08\x12\x1b\n\x16\x43HANGE_ZONE_PROPERTIES\x10\x87\x08\x12\x0e\n\tUNCONCEDE\x10\x88\x08\x12\n\n\x05JUDGE\x10\x89\x08\x12\x11\n\x0cREVERSE_TURN\x10\x8a\x08*\x08\x08\x64\x10\x80\x80\x80\x80\x02\"v\n\rCommand_Judge\x12\x15\n\ttarget_id\x18\x01 \x01(\x11:\x02-1\x12\"\n\x0cgame_command\x18\x02 \x03(\x0b\x32\x0c.GameCommand2*\n\x03\x65xt\x12\x0c.GameCommand\x18\x89\x08 \x01(\x0b\x32\x0e.Command_Judge'
)



_GAMECOMMAND_GAMECOMMANDTYPE = _descriptor.EnumDescriptor(
  name='GameCommandType',
  full_name='GameCommand.GameCommandType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KICK_FROM_GAME', index=0, number=1000,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEAVE_GAME', index=1, number=1001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GAME_SAY', index=2, number=1002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUFFLE', index=3, number=1003,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MULLIGAN', index=4, number=1004,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROLL_DIE', index=5, number=1005,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DRAW_CARDS', index=6, number=1006,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNDO_DRAW', index=7, number=1007,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLIP_CARD', index=8, number=1008,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ATTACH_CARD', index=9, number=1009,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREATE_TOKEN', index=10, number=1010,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ARROW', index=11, number=1011,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DELETE_ARROW', index=12, number=1012,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_CARD_ATTR', index=13, number=1013,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_CARD_COUNTER', index=14, number=1014,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INC_CARD_COUNTER', index=15, number=1015,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='READY_START', index=16, number=1016,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONCEDE', index=17, number=1017,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INC_COUNTER', index=18, number=1018,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CREATE_COUNTER', index=19, number=1019,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_COUNTER', index=20, number=1020,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEL_COUNTER', index=21, number=1021,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NEXT_TURN', index=22, number=1022,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_ACTIVE_PHASE', index=23, number=1023,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DUMP_ZONE', index=24, number=1024,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP_DUMP_ZONE', index=25, number=1025,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVEAL_CARDS', index=26, number=1026,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOVE_CARD', index=27, number=1027,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_SIDEBOARD_PLAN', index=28, number=1028,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DECK_SELECT', index=29, number=1029,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SET_SIDEBOARD_LOCK', index=30, number=1030,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHANGE_ZONE_PROPERTIES', index=31, number=1031,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNCONCEDE', index=32, number=1032,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='JUDGE', index=33, number=1033,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REVERSE_TURN', index=34, number=1034,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=40,
  serialized_end=706,
)
_sym_db.RegisterEnumDescriptor(_GAMECOMMAND_GAMECOMMANDTYPE)


_GAMECOMMAND = _descriptor.Descriptor(
  name='GameCommand',
  full_name='GameCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GAMECOMMAND_GAMECOMMANDTYPE,
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(100, 536870912), ],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=716,
)


_COMMAND_JUDGE = _descriptor.Descriptor(
  name='Command_Judge',
  full_name='Command_Judge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='target_id', full_name='Command_Judge.target_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_command', full_name='Command_Judge.game_command', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Command_Judge.ext', index=0,
      number=1033, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=718,
  serialized_end=836,
)

_GAMECOMMAND_GAMECOMMANDTYPE.containing_type = _GAMECOMMAND
_COMMAND_JUDGE.fields_by_name['game_command'].message_type = _GAMECOMMAND
DESCRIPTOR.message_types_by_name['GameCommand'] = _GAMECOMMAND
DESCRIPTOR.message_types_by_name['Command_Judge'] = _COMMAND_JUDGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameCommand = _reflection.GeneratedProtocolMessageType('GameCommand', (_message.Message,), {
  'DESCRIPTOR' : _GAMECOMMAND,
  '__module__' : 'game_commands_pb2'
  # @@protoc_insertion_point(class_scope:GameCommand)
  })
_sym_db.RegisterMessage(GameCommand)

Command_Judge = _reflection.GeneratedProtocolMessageType('Command_Judge', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_JUDGE,
  '__module__' : 'game_commands_pb2'
  # @@protoc_insertion_point(class_scope:Command_Judge)
  })
_sym_db.RegisterMessage(Command_Judge)

_COMMAND_JUDGE.extensions_by_name['ext'].message_type = _COMMAND_JUDGE
GameCommand.RegisterExtension(_COMMAND_JUDGE.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
