# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_event_container.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2
import game_event_context_pb2 as game__event__context__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='game_event_container.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1agame_event_container.proto\x1a\x10game_event.proto\x1a\x18game_event_context.proto\"\x9b\x01\n\x12GameEventContainer\x12\x0f\n\x07game_id\x18\x01 \x01(\r\x12\x1e\n\nevent_list\x18\x02 \x03(\x0b\x32\n.GameEvent\x12\"\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\x11.GameEventContext\x12\x17\n\x0fseconds_elapsed\x18\x04 \x01(\r\x12\x17\n\x0f\x66orced_by_judge\x18\x05 \x01(\r'
  ,
  dependencies=[game__event__pb2.DESCRIPTOR,game__event__context__pb2.DESCRIPTOR,])




_GAMEEVENTCONTAINER = _descriptor.Descriptor(
  name='GameEventContainer',
  full_name='GameEventContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='GameEventContainer.game_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_list', full_name='GameEventContainer.event_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='context', full_name='GameEventContainer.context', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seconds_elapsed', full_name='GameEventContainer.seconds_elapsed', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forced_by_judge', full_name='GameEventContainer.forced_by_judge', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=230,
)

_GAMEEVENTCONTAINER.fields_by_name['event_list'].message_type = game__event__pb2._GAMEEVENT
_GAMEEVENTCONTAINER.fields_by_name['context'].message_type = game__event__context__pb2._GAMEEVENTCONTEXT
DESCRIPTOR.message_types_by_name['GameEventContainer'] = _GAMEEVENTCONTAINER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameEventContainer = _reflection.GeneratedProtocolMessageType('GameEventContainer', (_message.Message,), {
  'DESCRIPTOR' : _GAMEEVENTCONTAINER,
  '__module__' : 'game_event_container_pb2'
  # @@protoc_insertion_point(class_scope:GameEventContainer)
  })
_sym_db.RegisterMessage(GameEventContainer)


# @@protoc_insertion_point(module_scope)
