# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game_event.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10game_event.proto\"\xe6\x04\n\tGameEvent\x12\x15\n\tplayer_id\x18\x01 \x01(\x11:\x02-1\"\xb7\x04\n\rGameEventType\x12\t\n\x04JOIN\x10\xe8\x07\x12\n\n\x05LEAVE\x10\xe9\x07\x12\x10\n\x0bGAME_CLOSED\x10\xea\x07\x12\x16\n\x11GAME_HOST_CHANGED\x10\xeb\x07\x12\x0b\n\x06KICKED\x10\xec\x07\x12\x17\n\x12GAME_STATE_CHANGED\x10\xed\x07\x12\x1e\n\x19PLAYER_PROPERTIES_CHANGED\x10\xef\x07\x12\r\n\x08GAME_SAY\x10\xf1\x07\x12\x11\n\x0c\x43REATE_ARROW\x10\xd0\x0f\x12\x11\n\x0c\x44\x45LETE_ARROW\x10\xd1\x0f\x12\x13\n\x0e\x43REATE_COUNTER\x10\xd2\x0f\x12\x10\n\x0bSET_COUNTER\x10\xd3\x0f\x12\x10\n\x0b\x44\x45L_COUNTER\x10\xd4\x0f\x12\x0f\n\nDRAW_CARDS\x10\xd5\x0f\x12\x11\n\x0cREVEAL_CARDS\x10\xd6\x0f\x12\x0c\n\x07SHUFFLE\x10\xd7\x0f\x12\r\n\x08ROLL_DIE\x10\xd8\x0f\x12\x0e\n\tMOVE_CARD\x10\xd9\x0f\x12\x0e\n\tFLIP_CARD\x10\xda\x0f\x12\x11\n\x0c\x44\x45STROY_CARD\x10\xdb\x0f\x12\x10\n\x0b\x41TTACH_CARD\x10\xdc\x0f\x12\x11\n\x0c\x43REATE_TOKEN\x10\xdd\x0f\x12\x12\n\rSET_CARD_ATTR\x10\xde\x0f\x12\x15\n\x10SET_CARD_COUNTER\x10\xdf\x0f\x12\x16\n\x11SET_ACTIVE_PLAYER\x10\xe0\x0f\x12\x15\n\x10SET_ACTIVE_PHASE\x10\xe1\x0f\x12\x0e\n\tDUMP_ZONE\x10\xe2\x0f\x12\x1b\n\x16\x43HANGE_ZONE_PROPERTIES\x10\xe4\x0f\x12\x11\n\x0cREVERSE_TURN\x10\xe5\x0f*\x08\x08\x64\x10\x80\x80\x80\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_event_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMEEVENT._serialized_start=21
  _GAMEEVENT._serialized_end=635
  _GAMEEVENT_GAMEEVENTTYPE._serialized_start=58
  _GAMEEVENT_GAMEEVENTTYPE._serialized_end=625
# @@protoc_insertion_point(module_scope)
