# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_deck_list.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_deckstorage_pb2 as serverinfo__deckstorage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18response_deck_list.proto\x1a\x0eresponse.proto\x1a\x1cserverinfo_deckstorage.proto\"n\n\x11Response_DeckList\x12,\n\x04root\x18\x01 \x01(\x0b\x32\x1e.ServerInfo_DeckStorage_Folder2+\n\x03\x65xt\x12\t.Response\x18\xee\x07 \x01(\x0b\x32\x12.Response_DeckList')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_deck_list_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_DECKLIST.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_DECKLIST._serialized_start=74
  _RESPONSE_DECKLIST._serialized_end=184
# @@protoc_insertion_point(module_scope)
