# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_register.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17response_register.proto\x1a\x0eresponse.proto\"t\n\x11Response_Register\x12\x19\n\x11\x64\x65nied_reason_str\x18\x01 \x01(\t\x12\x17\n\x0f\x64\x65nied_end_time\x18\x02 \x01(\x04\x32+\n\x03\x65xt\x12\t.Response\x18\xf1\x07 \x01(\x0b\x32\x12.Response_Register')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_register_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_REGISTER.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_REGISTER._serialized_start=43
  _RESPONSE_REGISTER._serialized_end=159
# @@protoc_insertion_point(module_scope)
