# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_warn_history.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_warning_pb2 as serverinfo__warning__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='response_warn_history.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bresponse_warn_history.proto\x1a\x0eresponse.proto\x1a\x18serverinfo_warning.proto\"n\n\x14Response_WarnHistory\x12&\n\twarn_list\x18\x01 \x03(\x0b\x32\x13.ServerInfo_Warning2.\n\x03\x65xt\x12\t.Response\x18\xf5\x07 \x01(\x0b\x32\x15.Response_WarnHistory'
  ,
  dependencies=[response__pb2.DESCRIPTOR,serverinfo__warning__pb2.DESCRIPTOR,])




_RESPONSE_WARNHISTORY = _descriptor.Descriptor(
  name='Response_WarnHistory',
  full_name='Response_WarnHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='warn_list', full_name='Response_WarnHistory.warn_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Response_WarnHistory.ext', index=0,
      number=1013, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=183,
)

_RESPONSE_WARNHISTORY.fields_by_name['warn_list'].message_type = serverinfo__warning__pb2._SERVERINFO_WARNING
DESCRIPTOR.message_types_by_name['Response_WarnHistory'] = _RESPONSE_WARNHISTORY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response_WarnHistory = _reflection.GeneratedProtocolMessageType('Response_WarnHistory', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_WARNHISTORY,
  '__module__' : 'response_warn_history_pb2'
  # @@protoc_insertion_point(class_scope:Response_WarnHistory)
  })
_sym_db.RegisterMessage(Response_WarnHistory)

_RESPONSE_WARNHISTORY.extensions_by_name['ext'].message_type = _RESPONSE_WARNHISTORY
response__pb2.Response.RegisterExtension(_RESPONSE_WARNHISTORY.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
