# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_replay_list.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_replay_match_pb2 as serverinfo__replay__match__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aresponse_replay_list.proto\x1a\x0eresponse.proto\x1a\x1dserverinfo_replay_match.proto\"q\n\x13Response_ReplayList\x12+\n\nmatch_list\x18\x01 \x03(\x0b\x32\x17.ServerInfo_ReplayMatch2-\n\x03\x65xt\x12\t.Response\x18\xcc\x08 \x01(\x0b\x32\x14.Response_ReplayList')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_replay_list_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_REPLAYLIST.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_REPLAYLIST._serialized_start=77
  _RESPONSE_REPLAYLIST._serialized_end=190
# @@protoc_insertion_point(module_scope)
