# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_warn_list.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18response_warn_list.proto\x1a\x0eresponse.proto\"{\n\x11Response_WarnList\x12\x0f\n\x07warning\x18\x01 \x03(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x15\n\ruser_clientid\x18\x03 \x01(\t2+\n\x03\x65xt\x12\t.Response\x18\xf6\x07 \x01(\x0b\x32\x12.Response_WarnList')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_warn_list_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_WARNLIST.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_WARNLIST._serialized_start=44
  _RESPONSE_WARNLIST._serialized_end=167
# @@protoc_insertion_point(module_scope)
