# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_dump_zone.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_zone_pb2 as serverinfo__zone__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='response_dump_zone.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18response_dump_zone.proto\x1a\x0eresponse.proto\x1a\x15serverinfo_zone.proto\"e\n\x11Response_DumpZone\x12#\n\tzone_info\x18\x01 \x01(\x0b\x32\x10.ServerInfo_Zone2+\n\x03\x65xt\x12\t.Response\x18\xec\x07 \x01(\x0b\x32\x12.Response_DumpZone'
  ,
  dependencies=[response__pb2.DESCRIPTOR,serverinfo__zone__pb2.DESCRIPTOR,])




_RESPONSE_DUMPZONE = _descriptor.Descriptor(
  name='Response_DumpZone',
  full_name='Response_DumpZone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='zone_info', full_name='Response_DumpZone.zone_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Response_DumpZone.ext', index=0,
      number=1004, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=168,
)

_RESPONSE_DUMPZONE.fields_by_name['zone_info'].message_type = serverinfo__zone__pb2._SERVERINFO_ZONE
DESCRIPTOR.message_types_by_name['Response_DumpZone'] = _RESPONSE_DUMPZONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response_DumpZone = _reflection.GeneratedProtocolMessageType('Response_DumpZone', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_DUMPZONE,
  '__module__' : 'response_dump_zone_pb2'
  # @@protoc_insertion_point(class_scope:Response_DumpZone)
  })
_sym_db.RegisterMessage(Response_DumpZone)

_RESPONSE_DUMPZONE.extensions_by_name['ext'].message_type = _RESPONSE_DUMPZONE
response__pb2.Response.RegisterExtension(_RESPONSE_DUMPZONE.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
