# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_replay_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_replay_match_pb2 as serverinfo__replay__match__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='response_replay_list.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aresponse_replay_list.proto\x1a\x0eresponse.proto\x1a\x1dserverinfo_replay_match.proto\"q\n\x13Response_ReplayList\x12+\n\nmatch_list\x18\x01 \x03(\x0b\x32\x17.ServerInfo_ReplayMatch2-\n\x03\x65xt\x12\t.Response\x18\xcc\x08 \x01(\x0b\x32\x14.Response_ReplayList'
  ,
  dependencies=[response__pb2.DESCRIPTOR,serverinfo__replay__match__pb2.DESCRIPTOR,])




_RESPONSE_REPLAYLIST = _descriptor.Descriptor(
  name='Response_ReplayList',
  full_name='Response_ReplayList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_list', full_name='Response_ReplayList.match_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='ext', full_name='Response_ReplayList.ext', index=0,
      number=1100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=190,
)

_RESPONSE_REPLAYLIST.fields_by_name['match_list'].message_type = serverinfo__replay__match__pb2._SERVERINFO_REPLAYMATCH
DESCRIPTOR.message_types_by_name['Response_ReplayList'] = _RESPONSE_REPLAYLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response_ReplayList = _reflection.GeneratedProtocolMessageType('Response_ReplayList', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_REPLAYLIST,
  '__module__' : 'response_replay_list_pb2'
  # @@protoc_insertion_point(class_scope:Response_ReplayList)
  })
_sym_db.RegisterMessage(Response_ReplayList)

_RESPONSE_REPLAYLIST.extensions_by_name['ext'].message_type = _RESPONSE_REPLAYLIST
response__pb2.Response.RegisterExtension(_RESPONSE_REPLAYLIST.extensions_by_name['ext'])

# @@protoc_insertion_point(module_scope)
