# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverinfo_card.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import serverinfo_cardcounter_pb2 as serverinfo__cardcounter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverinfo_card.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15serverinfo_card.proto\x1a\x1cserverinfo_cardcounter.proto\"\xe6\x02\n\x0fServerInfo_Card\x12\x0e\n\x02id\x18\x01 \x01(\x11:\x02-1\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x01x\x18\x03 \x01(\x11:\x02-1\x12\r\n\x01y\x18\x04 \x01(\x11:\x02-1\x12\x11\n\tface_down\x18\x05 \x01(\x08\x12\x0e\n\x06tapped\x18\x06 \x01(\x08\x12\x11\n\tattacking\x18\x07 \x01(\x08\x12\r\n\x05\x63olor\x18\x08 \x01(\t\x12\n\n\x02pt\x18\t \x01(\t\x12\x12\n\nannotation\x18\n \x01(\t\x12\x1e\n\x16\x64\x65stroy_on_zone_change\x18\x0b \x01(\x08\x12\x14\n\x0c\x64oesnt_untap\x18\x0c \x01(\x08\x12-\n\x0c\x63ounter_list\x18\r \x03(\x0b\x32\x17.ServerInfo_CardCounter\x12\x1c\n\x10\x61ttach_player_id\x18\x0e \x01(\x11:\x02-1\x12\x13\n\x0b\x61ttach_zone\x18\x0f \x01(\t\x12\x1a\n\x0e\x61ttach_card_id\x18\x10 \x01(\x11:\x02-1'
  ,
  dependencies=[serverinfo__cardcounter__pb2.DESCRIPTOR,])




_SERVERINFO_CARD = _descriptor.Descriptor(
  name='ServerInfo_Card',
  full_name='ServerInfo_Card',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ServerInfo_Card.id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ServerInfo_Card.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='ServerInfo_Card.x', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='ServerInfo_Card.y', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='face_down', full_name='ServerInfo_Card.face_down', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tapped', full_name='ServerInfo_Card.tapped', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attacking', full_name='ServerInfo_Card.attacking', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='ServerInfo_Card.color', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pt', full_name='ServerInfo_Card.pt', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='annotation', full_name='ServerInfo_Card.annotation', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destroy_on_zone_change', full_name='ServerInfo_Card.destroy_on_zone_change', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='doesnt_untap', full_name='ServerInfo_Card.doesnt_untap', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter_list', full_name='ServerInfo_Card.counter_list', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attach_player_id', full_name='ServerInfo_Card.attach_player_id', index=13,
      number=14, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attach_zone', full_name='ServerInfo_Card.attach_zone', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attach_card_id', full_name='ServerInfo_Card.attach_card_id', index=15,
      number=16, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=414,
)

_SERVERINFO_CARD.fields_by_name['counter_list'].message_type = serverinfo__cardcounter__pb2._SERVERINFO_CARDCOUNTER
DESCRIPTOR.message_types_by_name['ServerInfo_Card'] = _SERVERINFO_CARD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerInfo_Card = _reflection.GeneratedProtocolMessageType('ServerInfo_Card', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO_CARD,
  '__module__' : 'serverinfo_card_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo_Card)
  })
_sym_db.RegisterMessage(ServerInfo_Card)


# @@protoc_insertion_point(module_scope)
