# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverinfo_playerproperties.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import serverinfo_user_pb2 as serverinfo__user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverinfo_playerproperties.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!serverinfo_playerproperties.proto\x1a\x15serverinfo_user.proto\"\xe1\x01\n\x1bServerInfo_PlayerProperties\x12\x11\n\tplayer_id\x18\x01 \x01(\x11\x12#\n\tuser_info\x18\x02 \x01(\x0b\x32\x10.ServerInfo_User\x12\x11\n\tspectator\x18\x03 \x01(\x08\x12\x10\n\x08\x63onceded\x18\x04 \x01(\x08\x12\x13\n\x0bready_start\x18\x05 \x01(\x08\x12\x11\n\tdeck_hash\x18\x06 \x01(\t\x12\x14\n\x0cping_seconds\x18\x07 \x01(\x11\x12\x18\n\x10sideboard_locked\x18\x08 \x01(\x08\x12\r\n\x05judge\x18\t \x01(\x08'
  ,
  dependencies=[serverinfo__user__pb2.DESCRIPTOR,])




_SERVERINFO_PLAYERPROPERTIES = _descriptor.Descriptor(
  name='ServerInfo_PlayerProperties',
  full_name='ServerInfo_PlayerProperties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_id', full_name='ServerInfo_PlayerProperties.player_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_info', full_name='ServerInfo_PlayerProperties.user_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spectator', full_name='ServerInfo_PlayerProperties.spectator', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conceded', full_name='ServerInfo_PlayerProperties.conceded', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ready_start', full_name='ServerInfo_PlayerProperties.ready_start', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deck_hash', full_name='ServerInfo_PlayerProperties.deck_hash', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ping_seconds', full_name='ServerInfo_PlayerProperties.ping_seconds', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sideboard_locked', full_name='ServerInfo_PlayerProperties.sideboard_locked', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='judge', full_name='ServerInfo_PlayerProperties.judge', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=286,
)

_SERVERINFO_PLAYERPROPERTIES.fields_by_name['user_info'].message_type = serverinfo__user__pb2._SERVERINFO_USER
DESCRIPTOR.message_types_by_name['ServerInfo_PlayerProperties'] = _SERVERINFO_PLAYERPROPERTIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerInfo_PlayerProperties = _reflection.GeneratedProtocolMessageType('ServerInfo_PlayerProperties', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO_PLAYERPROPERTIES,
  '__module__' : 'serverinfo_playerproperties_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo_PlayerProperties)
  })
_sym_db.RegisterMessage(ServerInfo_PlayerProperties)


# @@protoc_insertion_point(module_scope)
