# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverinfo_ban.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverinfo_ban.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14serverinfo_ban.proto\"\x88\x01\n\x0eServerInfo_Ban\x12\x10\n\x08\x61\x64min_id\x18\x01 \x02(\t\x12\x12\n\nadmin_name\x18\x02 \x02(\t\x12\x10\n\x08\x62\x61n_time\x18\x03 \x02(\t\x12\x12\n\nban_length\x18\x04 \x02(\t\x12\x12\n\nban_reason\x18\x05 \x01(\t\x12\x16\n\x0evisible_reason\x18\x06 \x01(\t'
)




_SERVERINFO_BAN = _descriptor.Descriptor(
  name='ServerInfo_Ban',
  full_name='ServerInfo_Ban',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='admin_id', full_name='ServerInfo_Ban.admin_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='admin_name', full_name='ServerInfo_Ban.admin_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ban_time', full_name='ServerInfo_Ban.ban_time', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ban_length', full_name='ServerInfo_Ban.ban_length', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ban_reason', full_name='ServerInfo_Ban.ban_reason', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='visible_reason', full_name='ServerInfo_Ban.visible_reason', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['ServerInfo_Ban'] = _SERVERINFO_BAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerInfo_Ban = _reflection.GeneratedProtocolMessageType('ServerInfo_Ban', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO_BAN,
  '__module__' : 'serverinfo_ban_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo_Ban)
  })
_sym_db.RegisterMessage(ServerInfo_Ban)


# @@protoc_insertion_point(module_scope)
