# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverinfo_game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import serverinfo_user_pb2 as serverinfo__user__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverinfo_game.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15serverinfo_game.proto\x1a\x15serverinfo_user.proto\"\xdd\x03\n\x0fServerInfo_Game\x12\x15\n\tserver_id\x18\x01 \x01(\x11:\x02-1\x12\x13\n\x07room_id\x18\x02 \x01(\x11:\x02-1\x12\x13\n\x07game_id\x18\x03 \x01(\x11:\x02-1\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x15\n\rwith_password\x18\x05 \x01(\x08\x12\x13\n\x0bmax_players\x18\x06 \x01(\r\x12\x12\n\ngame_types\x18\x07 \x03(\x11\x12&\n\x0c\x63reator_info\x18\x08 \x01(\x0b\x32\x10.ServerInfo_User\x12\x14\n\x0conly_buddies\x18\t \x01(\x08\x12\x17\n\x0fonly_registered\x18\n \x01(\x08\x12\x1a\n\x12spectators_allowed\x18\x0b \x01(\x08\x12 \n\x18spectators_need_password\x18\x0c \x01(\x08\x12\x1b\n\x13spectators_can_chat\x18\r \x01(\x08\x12\x1d\n\x15spectators_omniscient\x18\x0e \x01(\x08\x12\x14\n\x0cplayer_count\x18\x1e \x01(\r\x12\x18\n\x10spectators_count\x18\x1f \x01(\r\x12\x0f\n\x07started\x18\x32 \x01(\x08\x12\x12\n\nstart_time\x18\x33 \x01(\r\x12\x0e\n\x06\x63losed\x18\x34 \x01(\x08'
  ,
  dependencies=[serverinfo__user__pb2.DESCRIPTOR,])




_SERVERINFO_GAME = _descriptor.Descriptor(
  name='ServerInfo_Game',
  full_name='ServerInfo_Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='ServerInfo_Game.server_id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='ServerInfo_Game.room_id', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='ServerInfo_Game.game_id', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='ServerInfo_Game.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='with_password', full_name='ServerInfo_Game.with_password', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_players', full_name='ServerInfo_Game.max_players', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_types', full_name='ServerInfo_Game.game_types', index=6,
      number=7, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creator_info', full_name='ServerInfo_Game.creator_info', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='only_buddies', full_name='ServerInfo_Game.only_buddies', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='only_registered', full_name='ServerInfo_Game.only_registered', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spectators_allowed', full_name='ServerInfo_Game.spectators_allowed', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spectators_need_password', full_name='ServerInfo_Game.spectators_need_password', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spectators_can_chat', full_name='ServerInfo_Game.spectators_can_chat', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spectators_omniscient', full_name='ServerInfo_Game.spectators_omniscient', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='player_count', full_name='ServerInfo_Game.player_count', index=14,
      number=30, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spectators_count', full_name='ServerInfo_Game.spectators_count', index=15,
      number=31, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='started', full_name='ServerInfo_Game.started', index=16,
      number=50, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='ServerInfo_Game.start_time', index=17,
      number=51, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='closed', full_name='ServerInfo_Game.closed', index=18,
      number=52, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=526,
)

_SERVERINFO_GAME.fields_by_name['creator_info'].message_type = serverinfo__user__pb2._SERVERINFO_USER
DESCRIPTOR.message_types_by_name['ServerInfo_Game'] = _SERVERINFO_GAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerInfo_Game = _reflection.GeneratedProtocolMessageType('ServerInfo_Game', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO_GAME,
  '__module__' : 'serverinfo_game_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo_Game)
  })
_sym_db.RegisterMessage(ServerInfo_Game)


# @@protoc_insertion_point(module_scope)
