# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverinfo_game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import serverinfo_user_pb2 as serverinfo__user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15serverinfo_game.proto\x1a\x15serverinfo_user.proto\"\xdd\x03\n\x0fServerInfo_Game\x12\x15\n\tserver_id\x18\x01 \x01(\x11:\x02-1\x12\x13\n\x07room_id\x18\x02 \x01(\x11:\x02-1\x12\x13\n\x07game_id\x18\x03 \x01(\x11:\x02-1\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x15\n\rwith_password\x18\x05 \x01(\x08\x12\x13\n\x0bmax_players\x18\x06 \x01(\r\x12\x12\n\ngame_types\x18\x07 \x03(\x11\x12&\n\x0c\x63reator_info\x18\x08 \x01(\x0b\x32\x10.ServerInfo_User\x12\x14\n\x0conly_buddies\x18\t \x01(\x08\x12\x17\n\x0fonly_registered\x18\n \x01(\x08\x12\x1a\n\x12spectators_allowed\x18\x0b \x01(\x08\x12 \n\x18spectators_need_password\x18\x0c \x01(\x08\x12\x1b\n\x13spectators_can_chat\x18\r \x01(\x08\x12\x1d\n\x15spectators_omniscient\x18\x0e \x01(\x08\x12\x14\n\x0cplayer_count\x18\x1e \x01(\r\x12\x18\n\x10spectators_count\x18\x1f \x01(\r\x12\x0f\n\x07started\x18\x32 \x01(\x08\x12\x12\n\nstart_time\x18\x33 \x01(\r\x12\x0e\n\x06\x63losed\x18\x34 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serverinfo_game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERINFO_GAME._serialized_start=49
  _SERVERINFO_GAME._serialized_end=526
# @@protoc_insertion_point(module_scope)
