# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverinfo_deckstorage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serverinfo_deckstorage.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cserverinfo_deckstorage.proto\"4\n\x1bServerInfo_DeckStorage_File\x12\x15\n\rcreation_time\x18\x01 \x01(\r\"P\n\x1dServerInfo_DeckStorage_Folder\x12/\n\x05items\x18\x01 \x03(\x0b\x32 .ServerInfo_DeckStorage_TreeItem\"\x97\x01\n\x1fServerInfo_DeckStorage_TreeItem\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\x04\x66ile\x18\n \x01(\x0b\x32\x1c.ServerInfo_DeckStorage_File\x12.\n\x06\x66older\x18\x0b \x01(\x0b\x32\x1e.ServerInfo_DeckStorage_Folder'
)




_SERVERINFO_DECKSTORAGE_FILE = _descriptor.Descriptor(
  name='ServerInfo_DeckStorage_File',
  full_name='ServerInfo_DeckStorage_File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='creation_time', full_name='ServerInfo_DeckStorage_File.creation_time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=84,
)


_SERVERINFO_DECKSTORAGE_FOLDER = _descriptor.Descriptor(
  name='ServerInfo_DeckStorage_Folder',
  full_name='ServerInfo_DeckStorage_Folder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ServerInfo_DeckStorage_Folder.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=166,
)


_SERVERINFO_DECKSTORAGE_TREEITEM = _descriptor.Descriptor(
  name='ServerInfo_DeckStorage_TreeItem',
  full_name='ServerInfo_DeckStorage_TreeItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ServerInfo_DeckStorage_TreeItem.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ServerInfo_DeckStorage_TreeItem.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file', full_name='ServerInfo_DeckStorage_TreeItem.file', index=2,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='folder', full_name='ServerInfo_DeckStorage_TreeItem.folder', index=3,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=320,
)

_SERVERINFO_DECKSTORAGE_FOLDER.fields_by_name['items'].message_type = _SERVERINFO_DECKSTORAGE_TREEITEM
_SERVERINFO_DECKSTORAGE_TREEITEM.fields_by_name['file'].message_type = _SERVERINFO_DECKSTORAGE_FILE
_SERVERINFO_DECKSTORAGE_TREEITEM.fields_by_name['folder'].message_type = _SERVERINFO_DECKSTORAGE_FOLDER
DESCRIPTOR.message_types_by_name['ServerInfo_DeckStorage_File'] = _SERVERINFO_DECKSTORAGE_FILE
DESCRIPTOR.message_types_by_name['ServerInfo_DeckStorage_Folder'] = _SERVERINFO_DECKSTORAGE_FOLDER
DESCRIPTOR.message_types_by_name['ServerInfo_DeckStorage_TreeItem'] = _SERVERINFO_DECKSTORAGE_TREEITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerInfo_DeckStorage_File = _reflection.GeneratedProtocolMessageType('ServerInfo_DeckStorage_File', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO_DECKSTORAGE_FILE,
  '__module__' : 'serverinfo_deckstorage_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo_DeckStorage_File)
  })
_sym_db.RegisterMessage(ServerInfo_DeckStorage_File)

ServerInfo_DeckStorage_Folder = _reflection.GeneratedProtocolMessageType('ServerInfo_DeckStorage_Folder', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO_DECKSTORAGE_FOLDER,
  '__module__' : 'serverinfo_deckstorage_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo_DeckStorage_Folder)
  })
_sym_db.RegisterMessage(ServerInfo_DeckStorage_Folder)

ServerInfo_DeckStorage_TreeItem = _reflection.GeneratedProtocolMessageType('ServerInfo_DeckStorage_TreeItem', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO_DECKSTORAGE_TREEITEM,
  '__module__' : 'serverinfo_deckstorage_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo_DeckStorage_TreeItem)
  })
_sym_db.RegisterMessage(ServerInfo_DeckStorage_TreeItem)


# @@protoc_insertion_point(module_scope)
