# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverinfo_cardcounter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cserverinfo_cardcounter.proto\"3\n\x16ServerInfo_CardCounter\x12\n\n\x02id\x18\x01 \x01(\x11\x12\r\n\x05value\x18\x02 \x01(\x11')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serverinfo_cardcounter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERINFO_CARDCOUNTER._serialized_start=32
  _SERVERINFO_CARDCOUNTER._serialized_end=83
# @@protoc_insertion_point(module_scope)
