# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serverinfo_arrow.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'serverinfo_arrow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import color_pb2 as color__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16serverinfo_arrow.proto\x1a\x0b\x63olor.proto\"\xc6\x01\n\x10ServerInfo_Arrow\x12\n\n\x02id\x18\x01 \x01(\x11\x12\x17\n\x0fstart_player_id\x18\x02 \x01(\x11\x12\x12\n\nstart_zone\x18\x03 \x01(\t\x12\x15\n\rstart_card_id\x18\x04 \x01(\x11\x12\x18\n\x10target_player_id\x18\x05 \x01(\x11\x12\x13\n\x0btarget_zone\x18\x06 \x01(\t\x12\x16\n\x0etarget_card_id\x18\x07 \x01(\x11\x12\x1b\n\x0b\x61rrow_color\x18\x08 \x01(\x0b\x32\x06.color')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serverinfo_arrow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERINFO_ARROW']._serialized_start=40
  _globals['_SERVERINFO_ARROW']._serialized_end=238
# @@protoc_insertion_point(module_scope)
