# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command_delete_arrow.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'command_delete_arrow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommand_delete_arrow.proto\x1a\x13game_commands.proto\"]\n\x13\x43ommand_DeleteArrow\x12\x14\n\x08\x61rrow_id\x18\x01 \x01(\x11:\x02-120\n\x03\x65xt\x12\x0c.GameCommand\x18\xf4\x07 \x01(\x0b\x32\x14.Command_DeleteArrow')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_delete_arrow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND_DELETEARROW']._serialized_start=51
  _globals['_COMMAND_DELETEARROW']._serialized_end=144
# @@protoc_insertion_point(module_scope)
