# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_set_active_phase.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ommand_set_active_phase.proto\x1a\x13game_commands.proto\"\\\n\x16\x43ommand_SetActivePhase\x12\r\n\x05phase\x18\x01 \x01(\r23\n\x03\x65xt\x12\x0c.GameCommand\x18\xff\x07 \x01(\x0b\x32\x17.Command_SetActivePhase')



_COMMAND_SETACTIVEPHASE = DESCRIPTOR.message_types_by_name['Command_SetActivePhase']
Command_SetActivePhase = _reflection.GeneratedProtocolMessageType('Command_SetActivePhase', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_SETACTIVEPHASE,
  '__module__' : 'command_set_active_phase_pb2'
  # @@protoc_insertion_point(class_scope:Command_SetActivePhase)
  })
_sym_db.RegisterMessage(Command_SetActivePhase)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_SETACTIVEPHASE.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_SETACTIVEPHASE._serialized_start=55
  _COMMAND_SETACTIVEPHASE._serialized_end=147
# @@protoc_insertion_point(module_scope)
