# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_draw_cards.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63ommand_draw_cards.proto\x1a\x13game_commands.proto\"S\n\x11\x43ommand_DrawCards\x12\x0e\n\x06number\x18\x01 \x01(\r2.\n\x03\x65xt\x12\x0c.GameCommand\x18\xee\x07 \x01(\x0b\x32\x12.Command_DrawCards')



_COMMAND_DRAWCARDS = DESCRIPTOR.message_types_by_name['Command_DrawCards']
Command_DrawCards = _reflection.GeneratedProtocolMessageType('Command_DrawCards', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DRAWCARDS,
  '__module__' : 'command_draw_cards_pb2'
  # @@protoc_insertion_point(class_scope:Command_DrawCards)
  })
_sym_db.RegisterMessage(Command_DrawCards)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_DRAWCARDS.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_DRAWCARDS._serialized_start=49
  _COMMAND_DRAWCARDS._serialized_end=132
# @@protoc_insertion_point(module_scope)
