# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_change_zone_properties.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$command_change_zone_properties.proto\x1a\x13game_commands.proto\"\xad\x01\n\x1c\x43ommand_ChangeZoneProperties\x12\x11\n\tzone_name\x18\x01 \x01(\t\x12\x1e\n\x16\x61lways_reveal_top_card\x18\n \x01(\x08\x12\x1f\n\x17\x61lways_look_at_top_card\x18\x0b \x01(\x08\x32\x39\n\x03\x65xt\x12\x0c.GameCommand\x18\x87\x08 \x01(\x0b\x32\x1d.Command_ChangeZoneProperties')



_COMMAND_CHANGEZONEPROPERTIES = DESCRIPTOR.message_types_by_name['Command_ChangeZoneProperties']
Command_ChangeZoneProperties = _reflection.GeneratedProtocolMessageType('Command_ChangeZoneProperties', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_CHANGEZONEPROPERTIES,
  '__module__' : 'command_change_zone_properties_pb2'
  # @@protoc_insertion_point(class_scope:Command_ChangeZoneProperties)
  })
_sym_db.RegisterMessage(Command_ChangeZoneProperties)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_CHANGEZONEPROPERTIES.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_CHANGEZONEPROPERTIES._serialized_start=62
  _COMMAND_CHANGEZONEPROPERTIES._serialized_end=235
# @@protoc_insertion_point(module_scope)
