# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_del_counter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ommand_del_counter.proto\x1a\x13game_commands.proto\"]\n\x12\x43ommand_DelCounter\x12\x16\n\ncounter_id\x18\x01 \x01(\x11:\x02-12/\n\x03\x65xt\x12\x0c.GameCommand\x18\xfd\x07 \x01(\x0b\x32\x13.Command_DelCounter')



_COMMAND_DELCOUNTER = DESCRIPTOR.message_types_by_name['Command_DelCounter']
Command_DelCounter = _reflection.GeneratedProtocolMessageType('Command_DelCounter', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DELCOUNTER,
  '__module__' : 'command_del_counter_pb2'
  # @@protoc_insertion_point(class_scope:Command_DelCounter)
  })
_sym_db.RegisterMessage(Command_DelCounter)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_DELCOUNTER.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_DELCOUNTER._serialized_start=50
  _COMMAND_DELCOUNTER._serialized_end=143
# @@protoc_insertion_point(module_scope)
