# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_deck_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_commands_pb2 as session__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ommand_deck_list.proto\x1a\x16session_commands.proto\"D\n\x10\x43ommand_DeckList20\n\x03\x65xt\x12\x0f.SessionCommand\x18\xf0\x07 \x01(\x0b\x32\x11.Command_DeckList')



_COMMAND_DECKLIST = DESCRIPTOR.message_types_by_name['Command_DeckList']
Command_DeckList = _reflection.GeneratedProtocolMessageType('Command_DeckList', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DECKLIST,
  '__module__' : 'command_deck_list_pb2'
  # @@protoc_insertion_point(class_scope:Command_DeckList)
  })
_sym_db.RegisterMessage(Command_DeckList)

if _descriptor._USE_C_DESCRIPTORS == False:
  session__commands__pb2.SessionCommand.RegisterExtension(_COMMAND_DECKLIST.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_DECKLIST._serialized_start=51
  _COMMAND_DECKLIST._serialized_end=119
# @@protoc_insertion_point(module_scope)
