# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_deck_new_dir.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_commands_pb2 as session__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommand_deck_new_dir.proto\x1a\x16session_commands.proto\"h\n\x12\x43ommand_DeckNewDir\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08\x64ir_name\x18\x02 \x01(\t22\n\x03\x65xt\x12\x0f.SessionCommand\x18\xf1\x07 \x01(\x0b\x32\x13.Command_DeckNewDir')



_COMMAND_DECKNEWDIR = DESCRIPTOR.message_types_by_name['Command_DeckNewDir']
Command_DeckNewDir = _reflection.GeneratedProtocolMessageType('Command_DeckNewDir', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DECKNEWDIR,
  '__module__' : 'command_deck_new_dir_pb2'
  # @@protoc_insertion_point(class_scope:Command_DeckNewDir)
  })
_sym_db.RegisterMessage(Command_DeckNewDir)

if _descriptor._USE_C_DESCRIPTORS == False:
  session__commands__pb2.SessionCommand.RegisterExtension(_COMMAND_DECKNEWDIR.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_DECKNEWDIR._serialized_start=54
  _COMMAND_DECKNEWDIR._serialized_end=158
# @@protoc_insertion_point(module_scope)
