# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_deck_del_dir.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_commands_pb2 as session__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ommand_deck_del_dir.proto\x1a\x16session_commands.proto\"V\n\x12\x43ommand_DeckDelDir\x12\x0c\n\x04path\x18\x01 \x01(\t22\n\x03\x65xt\x12\x0f.SessionCommand\x18\xf2\x07 \x01(\x0b\x32\x13.Command_DeckDelDir')



_COMMAND_DECKDELDIR = DESCRIPTOR.message_types_by_name['Command_DeckDelDir']
Command_DeckDelDir = _reflection.GeneratedProtocolMessageType('Command_DeckDelDir', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DECKDELDIR,
  '__module__' : 'command_deck_del_dir_pb2'
  # @@protoc_insertion_point(class_scope:Command_DeckDelDir)
  })
_sym_db.RegisterMessage(Command_DeckDelDir)

if _descriptor._USE_C_DESCRIPTORS == False:
  session__commands__pb2.SessionCommand.RegisterExtension(_COMMAND_DECKDELDIR.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_DECKDELDIR._serialized_start=54
  _COMMAND_DECKDELDIR._serialized_end=140
# @@protoc_insertion_point(module_scope)
