# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_replay_modify_match.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_commands_pb2 as session__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!command_replay_modify_match.proto\x1a\x16session_commands.proto\"\x80\x01\n\x19\x43ommand_ReplayModifyMatch\x12\x13\n\x07game_id\x18\x01 \x01(\x11:\x02-1\x12\x13\n\x0b\x64o_not_hide\x18\x02 \x01(\x08\x32\x39\n\x03\x65xt\x12\x0f.SessionCommand\x18\xce\x08 \x01(\x0b\x32\x1a.Command_ReplayModifyMatch')



_COMMAND_REPLAYMODIFYMATCH = DESCRIPTOR.message_types_by_name['Command_ReplayModifyMatch']
Command_ReplayModifyMatch = _reflection.GeneratedProtocolMessageType('Command_ReplayModifyMatch', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_REPLAYMODIFYMATCH,
  '__module__' : 'command_replay_modify_match_pb2'
  # @@protoc_insertion_point(class_scope:Command_ReplayModifyMatch)
  })
_sym_db.RegisterMessage(Command_ReplayModifyMatch)

if _descriptor._USE_C_DESCRIPTORS == False:
  session__commands__pb2.SessionCommand.RegisterExtension(_COMMAND_REPLAYMODIFYMATCH.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_REPLAYMODIFYMATCH._serialized_start=62
  _COMMAND_REPLAYMODIFYMATCH._serialized_end=190
# @@protoc_insertion_point(module_scope)
