# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_dump_zone.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ommand_dump_zone.proto\x1a\x13game_commands.proto\"\x9d\x01\n\x10\x43ommand_DumpZone\x12\x15\n\tplayer_id\x18\x01 \x01(\x11:\x02-1\x12\x11\n\tzone_name\x18\x02 \x01(\t\x12\x14\n\x0cnumber_cards\x18\x03 \x01(\x11\x12\x1a\n\x0bis_reversed\x18\x04 \x01(\x08:\x05\x66\x61lse2-\n\x03\x65xt\x12\x0c.GameCommand\x18\x80\x08 \x01(\x0b\x32\x11.Command_DumpZone')



_COMMAND_DUMPZONE = DESCRIPTOR.message_types_by_name['Command_DumpZone']
Command_DumpZone = _reflection.GeneratedProtocolMessageType('Command_DumpZone', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_DUMPZONE,
  '__module__' : 'command_dump_zone_pb2'
  # @@protoc_insertion_point(class_scope:Command_DumpZone)
  })
_sym_db.RegisterMessage(Command_DumpZone)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_DUMPZONE.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_DUMPZONE._serialized_start=49
  _COMMAND_DUMPZONE._serialized_end=206
# @@protoc_insertion_point(module_scope)
