# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command_set_card_attr.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'command_set_card_attr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2
import card_attributes_pb2 as card__attributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63ommand_set_card_attr.proto\x1a\x13game_commands.proto\x1a\x15\x63\x61rd_attributes.proto\"\xa1\x01\n\x13\x43ommand_SetCardAttr\x12\x0c\n\x04zone\x18\x01 \x01(\t\x12\x13\n\x07\x63\x61rd_id\x18\x02 \x01(\x11:\x02-1\x12!\n\tattribute\x18\x03 \x01(\x0e\x32\x0e.CardAttribute\x12\x12\n\nattr_value\x18\x04 \x01(\t20\n\x03\x65xt\x12\x0c.GameCommand\x18\xf5\x07 \x01(\x0b\x32\x14.Command_SetCardAttr')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_set_card_attr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND_SETCARDATTR']._serialized_start=76
  _globals['_COMMAND_SETCARDATTR']._serialized_end=237
# @@protoc_insertion_point(module_scope)
