# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_game_say.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommand_game_say.proto\x1a\x13game_commands.proto\"P\n\x0f\x43ommand_GameSay\x12\x0f\n\x07message\x18\x01 \x01(\t2,\n\x03\x65xt\x12\x0c.GameCommand\x18\xea\x07 \x01(\x0b\x32\x10.Command_GameSay')



_COMMAND_GAMESAY = DESCRIPTOR.message_types_by_name['Command_GameSay']
Command_GameSay = _reflection.GeneratedProtocolMessageType('Command_GameSay', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_GAMESAY,
  '__module__' : 'command_game_say_pb2'
  # @@protoc_insertion_point(class_scope:Command_GameSay)
  })
_sym_db.RegisterMessage(Command_GameSay)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_GAMESAY.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_GAMESAY._serialized_start=47
  _COMMAND_GAMESAY._serialized_end=127
# @@protoc_insertion_point(module_scope)
