# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command_mulligan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_commands_pb2 as game__commands__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ommand_mulligan.proto\x1a\x13game_commands.proto\"Q\n\x10\x43ommand_Mulligan\x12\x0e\n\x06number\x18\x07 \x01(\r2-\n\x03\x65xt\x12\x0c.GameCommand\x18\xec\x07 \x01(\x0b\x32\x11.Command_Mulligan')



_COMMAND_MULLIGAN = DESCRIPTOR.message_types_by_name['Command_Mulligan']
Command_Mulligan = _reflection.GeneratedProtocolMessageType('Command_Mulligan', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND_MULLIGAN,
  '__module__' : 'command_mulligan_pb2'
  # @@protoc_insertion_point(class_scope:Command_Mulligan)
  })
_sym_db.RegisterMessage(Command_Mulligan)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__commands__pb2.GameCommand.RegisterExtension(_COMMAND_MULLIGAN.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _COMMAND_MULLIGAN._serialized_start=47
  _COMMAND_MULLIGAN._serialized_end=128
# @@protoc_insertion_point(module_scope)
