# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_user_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_event_pb2 as session__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65vent_user_message.proto\x1a\x13session_event.proto\"\x81\x01\n\x11\x45vent_UserMessage\x12\x13\n\x0bsender_name\x18\x01 \x01(\t\x12\x15\n\rreceiver_name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2/\n\x03\x65xt\x12\r.SessionEvent\x18\xeb\x07 \x01(\x0b\x32\x12.Event_UserMessage')



_EVENT_USERMESSAGE = DESCRIPTOR.message_types_by_name['Event_UserMessage']
Event_UserMessage = _reflection.GeneratedProtocolMessageType('Event_UserMessage', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_USERMESSAGE,
  '__module__' : 'event_user_message_pb2'
  # @@protoc_insertion_point(class_scope:Event_UserMessage)
  })
_sym_db.RegisterMessage(Event_UserMessage)

if _descriptor._USE_C_DESCRIPTORS == False:
  session__event__pb2.SessionEvent.RegisterExtension(_EVENT_USERMESSAGE.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_USERMESSAGE._serialized_start=50
  _EVENT_USERMESSAGE._serialized_end=179
# @@protoc_insertion_point(module_scope)
