# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_list_rooms.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_event_pb2 as session__event__pb2
import serverinfo_room_pb2 as serverinfo__room__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65vent_list_rooms.proto\x1a\x13session_event.proto\x1a\x15serverinfo_room.proto\"e\n\x0f\x45vent_ListRooms\x12#\n\troom_list\x18\x01 \x03(\x0b\x32\x10.ServerInfo_Room2-\n\x03\x65xt\x12\r.SessionEvent\x18\xec\x07 \x01(\x0b\x32\x10.Event_ListRooms')



_EVENT_LISTROOMS = DESCRIPTOR.message_types_by_name['Event_ListRooms']
Event_ListRooms = _reflection.GeneratedProtocolMessageType('Event_ListRooms', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_LISTROOMS,
  '__module__' : 'event_list_rooms_pb2'
  # @@protoc_insertion_point(class_scope:Event_ListRooms)
  })
_sym_db.RegisterMessage(Event_ListRooms)

if _descriptor._USE_C_DESCRIPTORS == False:
  session__event__pb2.SessionEvent.RegisterExtension(_EVENT_LISTROOMS.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_LISTROOMS._serialized_start=70
  _EVENT_LISTROOMS._serialized_end=171
# @@protoc_insertion_point(module_scope)
