# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_delete_arrow.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65vent_delete_arrow.proto\x1a\x10game_event.proto\"S\n\x11\x45vent_DeleteArrow\x12\x10\n\x08\x61rrow_id\x18\x01 \x01(\x11\x32,\n\x03\x65xt\x12\n.GameEvent\x18\xd1\x0f \x01(\x0b\x32\x12.Event_DeleteArrow')



_EVENT_DELETEARROW = DESCRIPTOR.message_types_by_name['Event_DeleteArrow']
Event_DeleteArrow = _reflection.GeneratedProtocolMessageType('Event_DeleteArrow', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_DELETEARROW,
  '__module__' : 'event_delete_arrow_pb2'
  # @@protoc_insertion_point(class_scope:Event_DeleteArrow)
  })
_sym_db.RegisterMessage(Event_DeleteArrow)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_DELETEARROW.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_DELETEARROW._serialized_start=46
  _EVENT_DELETEARROW._serialized_end=129
# @@protoc_insertion_point(module_scope)
