# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_set_counter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65vent_set_counter.proto\x1a\x10game_event.proto\"b\n\x10\x45vent_SetCounter\x12\x12\n\ncounter_id\x18\x01 \x01(\x11\x12\r\n\x05value\x18\x02 \x01(\x11\x32+\n\x03\x65xt\x12\n.GameEvent\x18\xd3\x0f \x01(\x0b\x32\x11.Event_SetCounter')



_EVENT_SETCOUNTER = DESCRIPTOR.message_types_by_name['Event_SetCounter']
Event_SetCounter = _reflection.GeneratedProtocolMessageType('Event_SetCounter', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_SETCOUNTER,
  '__module__' : 'event_set_counter_pb2'
  # @@protoc_insertion_point(class_scope:Event_SetCounter)
  })
_sym_db.RegisterMessage(Event_SetCounter)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_SETCOUNTER.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_SETCOUNTER._serialized_start=45
  _EVENT_SETCOUNTER._serialized_end=143
# @@protoc_insertion_point(module_scope)
