# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_kicked.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65vent_kicked.proto\x1a\x10game_event.proto\"7\n\x0c\x45vent_Kicked2\'\n\x03\x65xt\x12\n.GameEvent\x18\xec\x07 \x01(\x0b\x32\r.Event_Kicked')



_EVENT_KICKED = DESCRIPTOR.message_types_by_name['Event_Kicked']
Event_Kicked = _reflection.GeneratedProtocolMessageType('Event_Kicked', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_KICKED,
  '__module__' : 'event_kicked_pb2'
  # @@protoc_insertion_point(class_scope:Event_Kicked)
  })
_sym_db.RegisterMessage(Event_Kicked)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_KICKED.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_KICKED._serialized_start=40
  _EVENT_KICKED._serialized_end=95
# @@protoc_insertion_point(module_scope)
