# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_set_card_attr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2
import card_attributes_pb2 as card__attributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65vent_set_card_attr.proto\x1a\x10game_event.proto\x1a\x15\x63\x61rd_attributes.proto\"\x9c\x01\n\x11\x45vent_SetCardAttr\x12\x11\n\tzone_name\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61rd_id\x18\x02 \x01(\x11\x12!\n\tattribute\x18\x03 \x01(\x0e\x32\x0e.CardAttribute\x12\x12\n\nattr_value\x18\x04 \x01(\t2,\n\x03\x65xt\x12\n.GameEvent\x18\xde\x0f \x01(\x0b\x32\x12.Event_SetCardAttr')



_EVENT_SETCARDATTR = DESCRIPTOR.message_types_by_name['Event_SetCardAttr']
Event_SetCardAttr = _reflection.GeneratedProtocolMessageType('Event_SetCardAttr', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_SETCARDATTR,
  '__module__' : 'event_set_card_attr_pb2'
  # @@protoc_insertion_point(class_scope:Event_SetCardAttr)
  })
_sym_db.RegisterMessage(Event_SetCardAttr)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_SETCARDATTR.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_SETCARDATTR._serialized_start=71
  _EVENT_SETCARDATTR._serialized_end=227
# @@protoc_insertion_point(module_scope)
