# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_set_active_phase.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65vent_set_active_phase.proto\x1a\x10game_event.proto\"V\n\x14\x45vent_SetActivePhase\x12\r\n\x05phase\x18\x01 \x01(\x11\x32/\n\x03\x65xt\x12\n.GameEvent\x18\xe1\x0f \x01(\x0b\x32\x15.Event_SetActivePhase')



_EVENT_SETACTIVEPHASE = DESCRIPTOR.message_types_by_name['Event_SetActivePhase']
Event_SetActivePhase = _reflection.GeneratedProtocolMessageType('Event_SetActivePhase', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_SETACTIVEPHASE,
  '__module__' : 'event_set_active_phase_pb2'
  # @@protoc_insertion_point(class_scope:Event_SetActivePhase)
  })
_sym_db.RegisterMessage(Event_SetActivePhase)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_SETACTIVEPHASE.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_SETACTIVEPHASE._serialized_start=50
  _EVENT_SETACTIVEPHASE._serialized_end=136
# @@protoc_insertion_point(module_scope)
