# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_game_say.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import game_event_pb2 as game__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x65vent_game_say.proto\x1a\x10game_event.proto\"J\n\rEvent_GameSay\x12\x0f\n\x07message\x18\x01 \x01(\t2(\n\x03\x65xt\x12\n.GameEvent\x18\xf1\x07 \x01(\x0b\x32\x0e.Event_GameSay')



_EVENT_GAMESAY = DESCRIPTOR.message_types_by_name['Event_GameSay']
Event_GameSay = _reflection.GeneratedProtocolMessageType('Event_GameSay', (_message.Message,), {
  'DESCRIPTOR' : _EVENT_GAMESAY,
  '__module__' : 'event_game_say_pb2'
  # @@protoc_insertion_point(class_scope:Event_GameSay)
  })
_sym_db.RegisterMessage(Event_GameSay)

if _descriptor._USE_C_DESCRIPTORS == False:
  game__event__pb2.GameEvent.RegisterExtension(_EVENT_GAMESAY.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _EVENT_GAMESAY._serialized_start=42
  _EVENT_GAMESAY._serialized_end=116
# @@protoc_insertion_point(module_scope)
