# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game_event_context.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'game_event_context.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18game_event_context.proto\"\xe8\x01\n\x10GameEventContext\"\xc9\x01\n\x0b\x43ontextType\x12\x10\n\x0bREADY_START\x10\xe8\x07\x12\x0c\n\x07\x43ONCEDE\x10\xe9\x07\x12\x10\n\x0b\x44\x45\x43K_SELECT\x10\xea\x07\x12\x0e\n\tUNDO_DRAW\x10\xeb\x07\x12\x0e\n\tMOVE_CARD\x10\xec\x07\x12\r\n\x08MULLIGAN\x10\xed\x07\x12\x11\n\x0cPING_CHANGED\x10\xee\x07\x12\x1d\n\x18\x43ONNECTION_STATE_CHANGED\x10\xef\x07\x12\x17\n\x12SET_SIDEBOARD_LOCK\x10\xf0\x07\x12\x0e\n\tUNCONCEDE\x10\xf1\x07*\x08\x08\x64\x10\x80\x80\x80\x80\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_event_context_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEEVENTCONTEXT']._serialized_start=29
  _globals['_GAMEEVENTCONTEXT']._serialized_end=261
  _globals['_GAMEEVENTCONTEXT_CONTEXTTYPE']._serialized_start=50
  _globals['_GAMEEVENTCONTEXT_CONTEXTTYPE']._serialized_end=251
# @@protoc_insertion_point(module_scope)
