# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_viewlog_history.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_chat_message_pb2 as serverinfo__chat__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresponse_viewlog_history.proto\x1a\x0eresponse.proto\x1a\x1dserverinfo_chat_message.proto\"z\n\x17Response_ViewLogHistory\x12,\n\x0blog_message\x18\x01 \x03(\x0b\x32\x17.ServerInfo_ChatMessage21\n\x03\x65xt\x12\t.Response\x18\xf7\x07 \x01(\x0b\x32\x18.Response_ViewLogHistory')



_RESPONSE_VIEWLOGHISTORY = DESCRIPTOR.message_types_by_name['Response_ViewLogHistory']
Response_ViewLogHistory = _reflection.GeneratedProtocolMessageType('Response_ViewLogHistory', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_VIEWLOGHISTORY,
  '__module__' : 'response_viewlog_history_pb2'
  # @@protoc_insertion_point(class_scope:Response_ViewLogHistory)
  })
_sym_db.RegisterMessage(Response_ViewLogHistory)

if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_VIEWLOGHISTORY.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_VIEWLOGHISTORY._serialized_start=81
  _RESPONSE_VIEWLOGHISTORY._serialized_end=203
# @@protoc_insertion_point(module_scope)
