# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: response_replay_list.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'response_replay_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_replay_match_pb2 as serverinfo__replay__match__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aresponse_replay_list.proto\x1a\x0eresponse.proto\x1a\x1dserverinfo_replay_match.proto\"q\n\x13Response_ReplayList\x12+\n\nmatch_list\x18\x01 \x03(\x0b\x32\x17.ServerInfo_ReplayMatch2-\n\x03\x65xt\x12\t.Response\x18\xcc\x08 \x01(\x0b\x32\x14.Response_ReplayList')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_replay_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSE_REPLAYLIST']._serialized_start=77
  _globals['_RESPONSE_REPLAYLIST']._serialized_end=190
# @@protoc_insertion_point(module_scope)
