# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_join_room.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_room_pb2 as serverinfo__room__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18response_join_room.proto\x1a\x0eresponse.proto\x1a\x15serverinfo_room.proto\"e\n\x11Response_JoinRoom\x12#\n\troom_info\x18\x01 \x01(\x0b\x32\x10.ServerInfo_Room2+\n\x03\x65xt\x12\t.Response\x18\xe8\x07 \x01(\x0b\x32\x12.Response_JoinRoom')



_RESPONSE_JOINROOM = DESCRIPTOR.message_types_by_name['Response_JoinRoom']
Response_JoinRoom = _reflection.GeneratedProtocolMessageType('Response_JoinRoom', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_JOINROOM,
  '__module__' : 'response_join_room_pb2'
  # @@protoc_insertion_point(class_scope:Response_JoinRoom)
  })
_sym_db.RegisterMessage(Response_JoinRoom)

if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_JOINROOM.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_JOINROOM._serialized_start=67
  _RESPONSE_JOINROOM._serialized_end=168
# @@protoc_insertion_point(module_scope)
