# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_ban_history.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_ban_pb2 as serverinfo__ban__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aresponse_ban_history.proto\x1a\x0eresponse.proto\x1a\x14serverinfo_ban.proto\"g\n\x13Response_BanHistory\x12!\n\x08\x62\x61n_list\x18\x01 \x03(\x0b\x32\x0f.ServerInfo_Ban2-\n\x03\x65xt\x12\t.Response\x18\xf4\x07 \x01(\x0b\x32\x14.Response_BanHistory')



_RESPONSE_BANHISTORY = DESCRIPTOR.message_types_by_name['Response_BanHistory']
Response_BanHistory = _reflection.GeneratedProtocolMessageType('Response_BanHistory', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_BANHISTORY,
  '__module__' : 'response_ban_history_pb2'
  # @@protoc_insertion_point(class_scope:Response_BanHistory)
  })
_sym_db.RegisterMessage(Response_BanHistory)

if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_BANHISTORY.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_BANHISTORY._serialized_start=68
  _RESPONSE_BANHISTORY._serialized_end=171
# @@protoc_insertion_point(module_scope)
