# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_list_users.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import serverinfo_user_pb2 as serverinfo__user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19response_list_users.proto\x1a\x0eresponse.proto\x1a\x15serverinfo_user.proto\"g\n\x12Response_ListUsers\x12#\n\tuser_list\x18\x01 \x03(\x0b\x32\x10.ServerInfo_User2,\n\x03\x65xt\x12\t.Response\x18\xe9\x07 \x01(\x0b\x32\x13.Response_ListUsers')



_RESPONSE_LISTUSERS = DESCRIPTOR.message_types_by_name['Response_ListUsers']
Response_ListUsers = _reflection.GeneratedProtocolMessageType('Response_ListUsers', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_LISTUSERS,
  '__module__' : 'response_list_users_pb2'
  # @@protoc_insertion_point(class_scope:Response_ListUsers)
  })
_sym_db.RegisterMessage(Response_ListUsers)

if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_LISTUSERS.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_LISTUSERS._serialized_start=68
  _RESPONSE_LISTUSERS._serialized_end=171
# @@protoc_insertion_point(module_scope)
