# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_get_admin_notes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresponse_get_admin_notes.proto\x1a\x0eresponse.proto\"l\n\x16Response_GetAdminNotes\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\r\n\x05notes\x18\x02 \x01(\t20\n\x03\x65xt\x12\t.Response\x18\xfa\x07 \x01(\x0b\x32\x17.Response_GetAdminNotes')



_RESPONSE_GETADMINNOTES = DESCRIPTOR.message_types_by_name['Response_GetAdminNotes']
Response_GetAdminNotes = _reflection.GeneratedProtocolMessageType('Response_GetAdminNotes', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE_GETADMINNOTES,
  '__module__' : 'response_get_admin_notes_pb2'
  # @@protoc_insertion_point(class_scope:Response_GetAdminNotes)
  })
_sym_db.RegisterMessage(Response_GetAdminNotes)

if _descriptor._USE_C_DESCRIPTORS == False:
  response__pb2.Response.RegisterExtension(_RESPONSE_GETADMINNOTES.extensions_by_name['ext'])

  DESCRIPTOR._options = None
  _RESPONSE_GETADMINNOTES._serialized_start=50
  _RESPONSE_GETADMINNOTES._serialized_end=158
# @@protoc_insertion_point(module_scope)
