# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_event.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10room_event.proto\"\x8e\x01\n\tRoomEvent\x12\x0f\n\x07room_id\x18\x01 \x01(\x11\"f\n\rRoomEventType\x12\x0f\n\nLEAVE_ROOM\x10\xe8\x07\x12\x0e\n\tJOIN_ROOM\x10\xe9\x07\x12\r\n\x08ROOM_SAY\x10\xea\x07\x12\x0f\n\nLIST_GAMES\x10\xeb\x07\x12\x14\n\x0fREMOVE_MESSAGES\x10\xec\x07*\x08\x08\x64\x10\x80\x80\x80\x80\x02')



_ROOMEVENT = DESCRIPTOR.message_types_by_name['RoomEvent']
_ROOMEVENT_ROOMEVENTTYPE = _ROOMEVENT.enum_types_by_name['RoomEventType']
RoomEvent = _reflection.GeneratedProtocolMessageType('RoomEvent', (_message.Message,), {
  'DESCRIPTOR' : _ROOMEVENT,
  '__module__' : 'room_event_pb2'
  # @@protoc_insertion_point(class_scope:RoomEvent)
  })
_sym_db.RegisterMessage(RoomEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOMEVENT._serialized_start=21
  _ROOMEVENT._serialized_end=163
  _ROOMEVENT_ROOMEVENTTYPE._serialized_start=51
  _ROOMEVENT_ROOMEVENTTYPE._serialized_end=153
# @@protoc_insertion_point(module_scope)
