# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverinfo_replay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17serverinfo_replay.proto\"Q\n\x11ServerInfo_Replay\x12\x15\n\treplay_id\x18\x01 \x01(\x11:\x02-1\x12\x13\n\x0breplay_name\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\r')



_SERVERINFO_REPLAY = DESCRIPTOR.message_types_by_name['ServerInfo_Replay']
ServerInfo_Replay = _reflection.GeneratedProtocolMessageType('ServerInfo_Replay', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO_REPLAY,
  '__module__' : 'serverinfo_replay_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo_Replay)
  })
_sym_db.RegisterMessage(ServerInfo_Replay)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERINFO_REPLAY._serialized_start=27
  _SERVERINFO_REPLAY._serialized_end=108
# @@protoc_insertion_point(module_scope)
