# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server_message.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'server_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import response_pb2 as response__pb2
import session_event_pb2 as session__event__pb2
import game_event_container_pb2 as game__event__container__pb2
import room_event_pb2 as room__event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14server_message.proto\x1a\x0eresponse.proto\x1a\x13session_event.proto\x1a\x1agame_event_container.proto\x1a\x10room_event.proto\"\xb1\x02\n\rServerMessage\x12\x30\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x1a.ServerMessage.MessageType\x12\x1b\n\x08response\x18\x02 \x01(\x0b\x32\t.Response\x12$\n\rsession_event\x18\x03 \x01(\x0b\x32\r.SessionEvent\x12\x31\n\x14game_event_container\x18\x04 \x01(\x0b\x32\x13.GameEventContainer\x12\x1e\n\nroom_event\x18\x05 \x01(\x0b\x32\n.RoomEvent\"X\n\x0bMessageType\x12\x0c\n\x08RESPONSE\x10\x00\x12\x11\n\rSESSION_EVENT\x10\x01\x12\x18\n\x14GAME_EVENT_CONTAINER\x10\x02\x12\x0e\n\nROOM_EVENT\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERMESSAGE']._serialized_start=108
  _globals['_SERVERMESSAGE']._serialized_end=413
  _globals['_SERVERMESSAGE_MESSAGETYPE']._serialized_start=325
  _globals['_SERVERMESSAGE_MESSAGETYPE']._serialized_end=413
# @@protoc_insertion_point(module_scope)
