# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverinfo_gametype.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19serverinfo_gametype.proto\"@\n\x13ServerInfo_GameType\x12\x14\n\x0cgame_type_id\x18\x01 \x01(\x11\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t')



_SERVERINFO_GAMETYPE = DESCRIPTOR.message_types_by_name['ServerInfo_GameType']
ServerInfo_GameType = _reflection.GeneratedProtocolMessageType('ServerInfo_GameType', (_message.Message,), {
  'DESCRIPTOR' : _SERVERINFO_GAMETYPE,
  '__module__' : 'serverinfo_gametype_pb2'
  # @@protoc_insertion_point(class_scope:ServerInfo_GameType)
  })
_sym_db.RegisterMessage(ServerInfo_GameType)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVERINFO_GAMETYPE._serialized_start=29
  _SERVERINFO_GAMETYPE._serialized_end=93
# @@protoc_insertion_point(module_scope)
